<html lang="pt-br" class="no-js">
<head>
    <!-- meta charec set -->
    <!--<meta charset="utf-8">-->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<!-- Always force latest IE rendering engine or request Chrome Frame -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<!-- Page Title -->
    <title>GTI CCHLA</title>
<!-- Meta Description -->
    <meta name="author" content="GESTÃO DE TI CCHLA">
<!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

<!-- CSS
================================================== -->

<!--
Fixed Navigation
==================================== -->
<!--
End Fixed Navigation
==================================== -->

<!--content-->
<?php echo $this->content(); ?>
<!-- End content-->

</html>
