<!-- Layout Dashboard-->
<!-- Bootstrap -->
<link href="../../App/View/css/bootstrap.min.css" rel="stylesheet">
<!-- Bootstrap Tour -->
<link href="../../App/View/css/bootstrap-tour.min.css" rel="stylesheet">
<link href="../../App/View/css/tour-popover.css" rel="stylesheet">
<!-- Font Awesome -->
<link href="../../App/View/css/fontawesome-all.min.css" rel="stylesheet">
<script defer src="../../App/View/js/fontawesome-all.min.js"></script>
<!-- NProgress -->
<link href="../../App/View/css/nprogress.css" rel="stylesheet">
<!-- iCheck -->
<link href="../../App/View/icheck/skins/square/blue.css" rel="stylesheet">
<!-- code prettifier -->
<link href="../../App/View/css/prettify.min.css" rel="stylesheet">
<!-- Select2 -->
<link href="../../App/View/css/select2.min.css" rel="stylesheet">
<!-- Switchery -->
<link href="../../App/View/css/switchery.min.css" rel="stylesheet">
<!-- starrr -->
<link href="../../App/View/css/starrr.css" rel="stylesheet">
<!-- bootstrap-daterangepicker -->
<link href="../../App/View/css/daterangepicker.css" rel="stylesheet">

<!-- Custom Theme Style -->
<link href="../../App/View/css/custom.min.css" rel="stylesheet">
<link href="../../App/View/css/base-style.css" rel="stylesheet">
<link href="../../App/View/css/custom-style-override.css" rel="stylesheet">
<link href="../../App/View/css/custom-modal.css" rel="stylesheet">
</head>

<body class="nav-md">
<div class="container body">
  <div class="main_container">

    <div class="col-md-3 left_col">
      <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
          <a href="../cliente" class="site_title"><img src="../../App/View/img/logo.svg" id="sidebar-logo" alt="Logo"><span id="sidebar-logo-text"><span>TI</span> <span>CCHLA</span></span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
          <div class="profile_pic">
            <img src="" alt="..." class="img-circle profile_img">
          </div>
          <div class="profile_info">
              <span>Bem-vindo,</span>
              <h2><?php echo $_SESSION['user_name'];?></h2>
          </div>
        </div>
        <!-- /menu profile quick info -->

        <br />

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
          <div class="menu_section">
            <h3></h3>
            <ul class="nav side-menu">
              <li>
                <a href="../cliente">
                  <span class="fa-layers fa-fw">
                    <i class="fas fa-home"></i>
                  </span> Início
                </a>
              </li>
              <li>
                <a href="./solicitar_atendimento">
                  <span class="fa-layers fa-fw">
                    <i class="fas fa-user"></i>
                    <i class="fas fa-wrench" data-fa-transform="shrink-4 down-4.2 right-7" style="color:#2DA7F9;"></i>
                  </span> Solicitar atendimento
                </a>
              </li>
              <li>
                <a href="./historico_chamados">
                  <span class="fa-layers fa-fw">
                    <i class="fas fa-list"></i>
                    <i class="fas fa-history  " data-fa-transform="shrink-4 down-12.2 right-9" style="color:#2DA7F9;"></i>
                </span> Histórico de chamados
                </a>
              </li>
            </ul>
          </div>

        </div>
        <!-- /sidebar menu -->

        <!-- /menu footer buttons -->
        <!--<div class="sidebar-footer hidden-small">
          <a data-toggle="tooltip" data-placement="top" title="Settings">
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
          </a>
          <a data-toggle="tooltip" data-placement="top" title="FullScreen">
            <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
          </a>
          <a data-toggle="tooltip" data-placement="top" title="Lock">
            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
          </a>
          <a data-toggle="tooltip" data-placement="top" title="Logout" href="../logout">
            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
          </a>
        </div>-->
        <!-- /menu footer buttons -->
      </div>
    </div>

    <!-- top navigation -->
    <div class="top_nav">
      <div class="nav_menu">
        <nav>
          <div class="nav toggle">
            <a id="menu_toggle"><i class="fas fa-bars"></i></a>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <i class="fas fa-user"></i> <?php echo $_SESSION['user_name'];?>
                <span class="fas fa-angle-down"></span>
              </a>
              <ul class="dropdown-menu dropdown-usermenu pull-right">
                <li>
                  <a href="./configuracoes" data-original-title="Configurações da conta">
                    <i class="fas fa-wrench pull-right"></i> Configurações da conta
                  </a>
                </li>
                <li>
                  <a href="../logout" data-original-title="Sair">
                    <i class="fas fa-sign-out-alt pull-right"></i> Sair
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </nav>
      </div>
    </div>
    <!-- /top navigation -->

    <!-- page content -->

    <div class="right_col" role="main">
      <div class="">
        <div class="page-title">
          <div class="row tile_count">

          </div>
          <div class="row">
            <div class="col-md-6 col-xs-12">
              <div id="nova-solicitacao-panel" class="x_panel">
                <div class="x_title">
                  <h2>NOVA SOLICITAÇÃO</h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fas fa-angle-up" data-fa-transform="grow-8"></i></a>
                    </li>
                    <!--<li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fas fa-cog"></i></a>
                      <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Settings 1</a>
                        </li>
                        <li><a href="#">Settings 2</a>
                        </li>
                      </ul>
                    </li>-->
                    <!-- <li><a class="close-link"><i class="fas fa-times"></i></a> -->
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                  <form class="form-horizontal form-label-left" method="post" action="client_register_call_request">

                    <div class="form-group">
                      <label class="control-label col-md-3 col-sm-3 col-xs-12">Motivo para atendimento</label>
                      <div class="col-md-9 col-sm-9 col-xs-12">
                        <select name="servico" class="select2_single form-control" tabindex="-1">
                          <option></option>
                          <?php foreach ($this->view->servicos as $servicos):?>
                            <option value=<?php echo $servicos['id'];?>><?php echo $servicos['nome'];?></option>
                          <?php endforeach; ?>
                        </select>
                      </div>
                    </div>
                    <div class="form-group">
                      <label class="control-label col-md-3 col-sm-3 col-xs-12">Descrição</label>
                      <div class="col-md-9 col-sm-9 col-xs-12">
                        <input type="text" name="descricao" class="form-control" placeholder="detalhes e observações">
                      </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                      <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                        <button type="reset" class="btn btn-default">Resetar campos</button>
                        <button type="submit" class="btn btn-default">Solicitar</button>
                      </div>
                    </div>

                  </form>
                </div>
              </div>
            </div>
            <div class="col-md-6 col-xs-12">
              <div id="solicitacoes-nao-abertas-panel" class="x_panel">
                <div class="x_title">
                  <h2>SOLICITAÇÕES<small>pendentes</small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fas fa-angle-up" data-fa-transform="grow-8"></i></a>
                    </li>
                    <!--<li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fas fa-cog"></i></a>
                    </li>-->
                    <!-- <li><a class="close-link"><i class="fas fa-times"></i></a> -->
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <form name="solicitacoes_chamado" method="post" action="">
                  <table id="call-request-list" class="table table-hover">
                    <thead>
                      <tr>
                        <th>ID</th>
                        <th>Data</th>
                        <th>Serviço</th>
                        <th>Status</th>
                        <th>Ação</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php foreach ($this->view->requisicoes as $requisicao):?>
                        <tr>
                            <td><?php echo $requisicao['id']; ?></td>
                            <td><?php $data = strtotime($requisicao['data_solicitacao']); $data = date('d/m/Y',$data); echo $data;?></td>
                            <td><?php echo $this->view->requests_services_names[$requisicao['id_servico']];?></td>
                            <td><?php echo $requisicao['status'];?></td>
                            <td> <input type="checkbox" value=<?php echo $requisicao['id'];?> name="selections[]"/></td>
                        </tr>
                      <?php endforeach;?>
                    </tbody>
                  </table>
                  <input type="hidden" name="delete_request" value="delete_request"/>
                  <button type="submit" class="btn btn-default" disabled>Excluir</button>
                </form>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
    </div>
    <!-- /page content -->

    <!-- footer content -->
    <!--<footer>

    </footer>-->
    <!-- /footer content -->
    <!-- SCRIPTS DASHBOARD THEME-->

  </div>

  <!-- REQUEST MODAL -->
  <div class="modal fade request-modal" tabindex="-1" role="dialog"></div>
</div>
<!-- jQuery -->
<script src="../../App/View/js/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="../../App/View/js/bootstrap.min.js"></script>
<!-- Bootstrap Tour -->
<script src="../../App/View/js/bootstrap-tour.min.js"></script>
<script src="../../App/View/js/cliente-tour.js"></script>
<script>
$(document).ready(function() {
  if (localStorage.getItem('tour_current_step') == "5") {
    tour.init();
    tour.start();
    tour.next();
  }
});
</script>
<!-- FastClick -->
<script src="../../App/View/js/fastclick.js"></script>
<!-- NProgress -->
<script src="../../App/View/js/nprogress.js"></script>
<!-- iCheck -->
<script src="../../App/View/js/icheck.min.js"></script>
<script>
$(document).ready(function(){
  $('input').iCheck({
    checkboxClass: 'icheckbox_square-blue',
    radioClass: 'iradio_square'
  });
});
</script>
<!-- bootstrap-daterangepicker -->
<script src="../../App/View/js/moment.min.js"></script>
<script src="../../App/View/js/daterangepicker.js"></script>
<!-- bootstrap-wysiwyg -->
<script src="../../App/View/js/bootstrap-wysiwyg.min.js"></script>
<script src="../../App/View/js/jquery.hotkeys.js"></script>
<script src="../../App/View/js/prettify.js"></script>
<!-- jQuery Tags Input -->
<script src="../../App/View/js/jquery.tagsinput.js"></script>
<!-- Switchery -->
<script src="../../App/View/js/switchery.min.js"></script>
<!-- Select2 -->
<script src="../../App/View/js/select2.full.min.js"></script>
<!-- Parsley -->
<script src="../../App/View/js/parsley.min.js"></script>
<!-- Autosize -->
<script src="../../App/View/js/autosize.min.js"></script>
<!-- jQuery autocomplete -->
<script src="../../App/View/js/jquery.autocomplete.min.js"></script>
<!-- starrr -->
<script src="../../App/View/js/starrr.js"></script>
<!-- Custom Theme Scripts -->
<script src="../../App/View/js/custom.min.js"></script>

<!-- Request modal settings -->
<script src="../../App/View/js/request-modals.js"></script>
<script>
$('#call-request-list tr').on('click', function(e) {
  modal_form_config = {
    id_solicitacao_field: true,
    cliente_field: true,
    solicitacao_chamado_status_field: true,
    servico_field: true,
    data_solicitacao_field: true,
    descricao_field: true
  };
  defineAndShowModal("call-request-type", e, modal_form_config);
});
</script>

<!-- Check if there's request checked -->
<script>

var btn_del_request = $('form[name=solicitacoes_chamado] > button[type=submit]');

$('form[name=solicitacoes_chamado] input').on('ifChecked', function(event) {
  if (btn_del_request.hasClass('btn-default')) {
    btn_del_request.toggleClass('btn-default btn-primary');
    btn_del_request.prop('disabled', function(i, v) { return !v; });
  }
});

$('form[name=solicitacoes_chamado] input').on('ifUnchecked', function(event) {
  var all_unchecked = true;
  var form_inputs = $('form[name=solicitacoes_chamado] input[type=checkbox]');

  form_inputs.each(function() {
    if (this.checked) {
      all_unchecked = false;
    }
  });

  if (all_unchecked) {
    btn_del_request.toggleClass('btn-default btn-primary');
    btn_del_request.prop('disabled', function(i, v) { return !v; });
  }
});
</script>
</body>
