<!-- Layout Dashboard-->
<!-- Bootstrap -->
<link href="../../App/View/css/bootstrap.min.css" rel="stylesheet">
<!-- Font Awesome -->
<link href="../../App/View/css/fontawesome-all.min.css" rel="stylesheet">
<script defer src="../../App/View/js/fontawesome-all.min.js"></script>
<!-- Custom Theme Style -->
<link href="../../App/View/css/custom.min.css" rel="stylesheet">
<link href="../../App/View/css/base-style.css" rel="stylesheet">
<link href="../../App/View/css/custom-style-override.css" rel="stylesheet">
<link href="../../App/View/css/custom-modal.css" rel="stylesheet">
<link href="../../App/View/css/request-modal.css" rel="stylesheet">
</head>

<body class="nav-md">
  <div class="container body">
    <div class="main_container">

      <div class="col-md-3 left_col">
        <div class="left_col scroll-view">
          <div class="navbar nav_title" style="border: 0;">
            <a href="../cliente" class="site_title"><img src="../../App/View/img/logo.svg" id="sidebar-logo" alt="Logo"><span id="sidebar-logo-text"><span>TI</span> <span>CCHLA</span></span></a>
          </div>

          <div class="clearfix"></div>

          <!-- menu profile quick info -->
          <div class="profile clearfix">
            <div class="profile_pic">
              <img src="" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
              <span>Bem-vindo,</span>
              <h2><?php echo $_SESSION['user_name'];?></h2>
            </div>
          </div>
          <!-- /menu profile quick info -->

          <br />

          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
              <h3></h3>
              <ul class="nav side-menu">
                <li>
                  <a href="../cliente">
                    <span class="fa-layers fa-fw">
                      <i class="fas fa-home"></i>
                    </span> Início
                  </a>
                </li>
                <li>
                  <a href="./solicitar_atendimento">
                    <span class="fa-layers fa-fw">
                      <i class="fas fa-user"></i>
                      <i class="fas fa-wrench" data-fa-transform="shrink-4 down-4.2 right-7" style="color:#2DA7F9;"></i>
                    </span> Solicitar atendimento
                  </a>
                </li>
                <li>
                  <a href="./historico_chamados">
                    <span class="fa-layers fa-fw">
                      <i class="fas fa-list"></i>
                      <i class="fas fa-history  " data-fa-transform="shrink-4 down-12.2 right-9" style="color:#2DA7F9;"></i>
                  </span> Histórico de chamados
                  </a>
                </li>
              </ul>
            </div>

          </div>
        </div>
      </div>

      <!-- top navigation -->
      <div class="top_nav">
        <div class="nav_menu">
          <nav>
            <div class="nav toggle">
              <a id="menu_toggle"><i class="fas fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
              <li>
                <a href="" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                  <i class="fas fa-user"></i> <?php echo $_SESSION['user_name'];?>
                  <span class="fas fa-angle-down"></span>
                </a>
                <ul class="dropdown-menu dropdown-usermenu pull-right">
                  <li>
                    <a href="./configuracoes" data-original-title="Configurações da conta">
                      <i class="fas fa-wrench pull-right"></i> Configurações da conta
                    </a>
                  </li>
                  <li>
                    <a href="../logout" data-original-title="Sair">
                      <i class="fas fa-sign-out-alt pull-right"></i> Sair
                    </a>
                  </li>
                </ul>
              </li>
            </ul>
          </nav>
        </div>
      </div>
      <!-- /top navigation -->

      <!-- page content -->

      <div class="right_col" role="main">
        <div class="">
          <div class="page-title">
            <div class="title_left" style="margin-bottom:20px;">
              <h3>Histórico dos meus chamados</h3>
            </div>
          </div>
          <div class="clearfix"></div>

          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_content">
                  <form name="form_historico_chamados_cliente" method="post" action="">
                  <table id="closed-requests" class="table table-hover clickable-rows">
                    <thead>
                      <tr>
                        <th>ID</th>
                        <th>Local</th>
                        <th>Serviço</th>
                        <th>Técnico Abertura</th>
                        <th>Status</th>
                      </tr>
                    </thead>
                    <tbody></tbody>
                  </table>
                </form>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
    </div>
    <!-- /page content -->

    <!-- footer content -->
    <!--<footer>

    </footer>-->
    <!-- /footer content -->
    <!-- SCRIPTS DASHBOARD THEME-->

  </div>

  <!-- REQUEST MODAL -->
  <div class="modal fade request-modal" tabindex="-1" role="dialog"></div>

  <!-- jQuery -->
  <script src="../../App/View/js/jquery.min.js"></script>
  <!-- Bootstrap -->
  <script src="../../App/View/js/bootstrap.min.js"></script>

  <!-- Moment.js -->
  <script src="../../App/View/js/moment.min.js"></script>

  <!-- Custom Theme Scripts -->
  <script src="../../App/View/js/custom.min.js"></script>

  <!-- Request modal settings -->
  <script src="../../App/View/js/request-modals.js"></script>
  <script>
    function clickRequestRow(e) {
      if (e.target.nodeName == "TR" || e.target.nodeName == "TD") {
        var requestId = getRowId(e);
        if (requestId) {
          modalConfig = {
            title: "Detalhes do chamado",
            visible_fields: {
              id_chamado_field: true,
              status_field: true,
              cliente_field: true,
              local_field: true,
              servico_field: true,
              tombo_field: true,
              data_abertura_field: true,
              data_assumido_field: true,
              data_finalizado_field: true,
              tecnico_abertura_field: true,
              descricao_field: true,
              prazo_field: true,
              parecer_tecnico_field: true,
              responsaveis_field: true
            }
          };
          let requestData = inactiveTickets.find(r => r.id_chamado === requestId);
          defineSimpleModal(modalConfig, requestData);
        }
      }
    }
  </script>

  <!-- Table handling -->
  <script>
    function insertInInactiveTicketsTable(request) {
      let pastRequestsTable = $('#closed-requests');

      // Row structure
      let newRow = $("<tr>").attr("data-request-id", request.id_chamado);
      let cols = "";
      cols += `<td>${request.id_chamado}</td>`;
      cols += `<td>${request.local}</td>`;
      cols += `<td>${request.servico}</td>`;
      cols += `<td>${request.tecnico_abertura}</td>`;
      cols += `<td>${request.status}</td>`;
      newRow.append(cols);

      // Events
      $(newRow).on('click', clickRequestRow);

      // Add the row to the table
      pastRequestsTable.prepend(newRow);
    }
  </script>

  <!-- Ready -->
  <script>
    const populateInactiveTicketsTable = () => {
      // Take only the requests already resolved (all status except "AGUARDANDO" and "ATENDIMENTO")
      let pastRequests = inactiveTickets.filter(r =>
        r.status !== "AGUARDANDO" && r.status !== "ATENDIMENTO");
      for (request of pastRequests) {
        insertInInactiveTicketsTable(request);
      }
    };

    $(document).ready(function() {
      // Load the requests for the page
      window.inactiveTickets = <?php echo json_encode($this->view->inactiveTickets) ?>;

      // Fill up unopen requests table
      populateInactiveTicketsTable();
    });
  </script>
</body>
