<!-- Layout Dashboard-->
<!-- Bootstrap -->
<link href="../App/View/css/bootstrap.min.css" rel="stylesheet">
<!-- Bootstrap Tour -->
<link href="../App/View/css/bootstrap-tour.min.css" rel="stylesheet">
<link href="../App/View/css/tour-popover.css" rel="stylesheet">
<!-- Font Awesome -->
<link href="../App/View/css/fontawesome-all.min.css" rel="stylesheet">
<script defer src="../App/View/js/fontawesome-all.min.js"></script>
<!-- NProgress -->
<link href="../App/View/css/nprogress.css" rel="stylesheet">
<!-- Custom Theme Style -->
<link href="../App/View/css/custom.min.css" rel="stylesheet">
<link href="../App/View/css/base-style.css" rel="stylesheet">
<link href="../App/View/css/custom-style-override.css" rel="stylesheet">
<link href="../App/View/css/custom-modal.css" rel="stylesheet">
</head>

<body class="nav-md">
<div class="container body">
  <div class="main_container">

    <div class="col-md-3 left_col">
      <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
          <a href="./cliente" class="site_title"><img src="../App/View/img/logo.svg" id="sidebar-logo" alt="Logo"><span id="sidebar-logo-text"><span>TI</span> <span>CCHLA</span></span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
          <div class="profile_pic">
            <img src="" alt="..." class="img-circle profile_img">
          </div>
          <div class="profile_info">
            <span>Bem-vindo,</span>
            <h2><?php echo $_SESSION['user_name'];?></h2>
          </div>
        </div>
        <!-- /menu profile quick info -->

        <br />

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
          <div class="menu_section">
            <h3></h3>
            <ul class="nav side-menu">
              <li>
                <a href="./cliente">
                  <span class="fa-layers fa-fw">
                    <i class="fas fa-home"></i>
                  </span> Início
                </a>
              </li>
              <li>
                <a href="cliente/solicitar_atendimento">
                  <span class="fa-layers fa-fw">
                    <i class="fas fa-user"></i>
                    <i class="fas fa-wrench" data-fa-transform="shrink-4 down-4.2 right-7" style="color:#2DA7F9;"></i>
                  </span> Solicitar atendimento
                </a>
              </li>
              <li>
                <a href="cliente/historico_chamados">
                  <span class="fa-layers fa-fw">
                    <i class="fas fa-list"></i>
                    <i class="fas fa-history  " data-fa-transform="shrink-4 down-12.2 right-9" style="color:#2DA7F9;"></i>
                </span> Histórico de chamados
                </a>
              </li>
            </ul>
          </div>

        </div>
      </div>
    </div>

    <!-- top navigation -->
    <div class="top_nav">
      <div class="nav_menu">
        <nav>
          <div class="nav toggle">
            <a id="menu_toggle"><i class="fas fa-bars"></i></a>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <i class="fas fa-user"></i> <?php echo $_SESSION['user_name'];?>
                <span class="fas fa-angle-down"></span>
              </a>
              <ul class="dropdown-menu dropdown-usermenu pull-right">
                <li>
                  <a href="cliente/configuracoes" data-original-title="Configurações da conta">
                    <i class="fas fa-wrench pull-right"></i> Configurações da conta
                  </a>
                </li>
                <li>
                  <a href="logout" data-original-title="Sair">
                    <i class="fas fa-sign-out-alt pull-right"></i> Sair
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </nav>
      </div>
    </div>
    <!-- /top navigation -->

    <!-- page content -->

    <div class="right_col" role="main">
      <div class="">
        <div class="page-title">
          <div class="row tile_count">

          </div>
          <div class="row">
            <div class="col-md-6 col-xs-12">
              <div id="chamados-em-atendimento-panel" class="x_panel">
                <div class="x_title">
                  <h2>CHAMADOS<small>Em atendimento</small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fas fa-angle-up" data-fa-transform="grow-8"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <form name="chamados_atendimento_clientes" method="post" action="">
                  <table id="processing-requests" class="table table-hover clickable-rows">
                    <thead>
                      <tr>
                        <th>ID</th>
                        <th>Serviço</th>
                        <th>Prazo</th>
                        <th>Técnico Responsável</th>
                        <th>Técnico Abertura</th>
                      </tr>
                    </thead>
                    <tbody></tbody>
                  </table>
                </form>
                </div>
              </div>
            </div>
            <div class="col-md-6 col-xs-12">
              <div id="chamados-abertos-panel" class="x_panel">
                <div class="x_title">
                  <h2>NA FILA<small>para atendimento</small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fas fa-angle-up" data-fa-transform="grow-8"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <form name="chamados_abertos_clientes" method="post" action="">
                  <table id="not-processing-requests" class="table table-hover  clickable-rows">
                    <thead>
                      <tr>
                        <th>ID</th>
                        <th>Serviço</th>
                        <th>Prazo</th>
                        <th>Técnico Abertura</th>
                        <th>Ação</th>
                      </tr>
                    </thead>
                    <tbody></tbody>
                  </table>
                </form>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
    </div>
    <!-- /page content -->

    <!-- footer content -->
    <!--<footer>

    </footer>-->
    <!-- /footer content -->
    <!-- SCRIPTS DASHBOARD THEME-->

  </div>

  <!-- REQUEST MODAL -->
  <div class="modal fade request-modal" tabindex="-1" role="dialog"></div>
</div>
<!-- jQuery -->
<script src="../App/View/js/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="../App/View/js/bootstrap.min.js"></script>
<!-- Bootstrap Tour -->
<script src="../App/View/js/bootstrap-tour.min.js"></script>
<script src="../App/View/js/cliente-tour.js"></script>
<!-- NProgress -->
<script src="../App/View/js/nprogress.js"></script>
<!-- Moment.js -->
<script src="../App/View/js/moment.min.js"></script>
<!-- forge-sha256 -->
<script src="../App/View/js/forge-sha256.min.js"></script>

<!-- Socket.IO -->
<script src="../App/View/js/socket.io.js"></script>
<script>
  let token = <?php echo $this->view->token ?>;

  // Connect to the WebSocket server
  let socket = io(`wss://${window.location.host}:5530`);

  // Try to resolve the challenge in order to stay connected to the WS server
  socket.on('connecting', ({challenge}) => {
    let solution = `${challenge}${token.last_login_date}`;
    let tokenData = {
      "username": token.username,
      "challengeSolution": forge_sha256(solution)
    };
    socket.emit('challenge solution', tokenData);
  });

  // When the support creates a ticket directly
  socket.on('support created ticket', ticket => {
    // Insert the ticket into the "in queue" list and table
    window.inQueueTickets.push(ticket);
    insertInOpenedRequestsTable(ticket);
  });

  // When the support accepts a ticket request
  socket.on('support accepted ticket request', ticket => {
    // Insert the ticket into the "in queue" list and table
    window.inQueueTickets.push(ticket);
    insertInOpenedRequestsTable(ticket);
  });

  // When a technician assumes a ticket
  socket.on('technician acquired ticket', ticket => {
    // Move the ticket from the "in queue" table to the "in process" one

    // Remove the old ticket from the "in queue" list
    window.inQueueTickets = window.inQueueTickets.filter(
      r => r.id_chamado !== ticket.id_chamado
    );

    // Remove the old ticket from the "in queue" table
    $('form[name=chamados_abertos_clientes]').find(`[data-request-id=${ticket.id_chamado}]`).remove();

    // Insert the ticket with new data in the "in process" list and table
    window.inProcessTickets.push(ticket);
    insertInProcessingRequestsTable(ticket);
  });

  // When a technician finalizes a ticket
  socket.on('technician finalized ticket', ticket => {
    // Remove the ticket from the "in process" list and table
    window.inProcessTickets = window.inProcessTickets.filter(
      r => r.id_chamado !== ticket.id_chamado
    );
    $('form[name=chamados_atendimento_clientes]').find(`[data-request-id=${ticket.id_chamado}]`).remove();
  });
</script>

<!-- Custom Theme Scripts -->
<script src="../App/View/js/custom.min.js"></script>

<!-- Request modal settings -->
<script src="../App/View/js/request-modals.js"></script>
<script>
  function clickInProcessRequestTableRow(e) {
    if (e.target.nodeName == "TR" || e.target.nodeName == "TD") {
      let requestId = getRowId(e);
      if (requestId) {
        modalConfig = {
          title: "Detalhes do chamado",
          visible_fields: {
            id_chamado_field: true,
            local_field: true,
            status_field: true,
            servico_field: true,
            data_abertura_field: true,
            data_assumido_field: true,
            tecnico_abertura_field: true,
            descricao_field: true,
            prazo_field: true,
            tecnico_responsavel_field: true
          }
        };
        let requestData = inProcessTickets.find(r => r.id_chamado === requestId);
        defineSimpleModal(modalConfig, requestData);
      }
    }
  }
  function clickOpenedRequestTableRow(e) {
    if (e.target.nodeName == "TR" || e.target.nodeName == "TD") {
      var requestId = getRowId(e);
      if (requestId) {
        modalConfig = {
          title: "Detalhes do chamado",
          visible_fields: {
            id_chamado_field: true,
            local_field: true,
            status_field: true,
            servico_field: true,
            data_abertura_field: true,
            tecnico_abertura_field: true,
            descricao_field: true,
            prazo_field: true
          }
        };
        let requestData = inQueueTickets.find(r => r.id_chamado === requestId);
        defineSimpleModal(modalConfig, requestData);
      }
    }
  }
</script>

<!-- Simple message modal -->
<div class="modal fade" id="simple-modal" tabindex="-1" role="dialog" data-backdrop="false">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="simple-modal-title">Modal title</h4>
      </div>
      <div class="modal-body" id="simple-modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button id="simple-modal-secondary-button" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button id="simple-modal-primary-button" type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<script>
  function setSimpleModalContent(title, body, primaryButtonAction, primaryButtonText = "Confirmar", secondaryButtonText = "Cancelar") {
    $('#simple-modal-title')[0].innerHTML = title;
    $('#simple-modal-body')[0].innerHTML = body;
    $('#simple-modal-primary-button')[0].innerHTML = primaryButtonText;
    $('#simple-modal-primary-button').off('click');
    $('#simple-modal-primary-button').on('click', primaryButtonAction);
    $('#simple-modal-secondary-button')[0].innerHTML = secondaryButtonText;
  }
</script>

<!-- Archive request confirmation -->
<script>
  const cancelRequest = (requestId) => {
    // Block the page
    $("html").css("cursor", "wait");
    $("body").css("pointer-events", "none");

    $.post("/gtic/public/cliente/client_cancel_call_request", {
      "request_id": requestId,
      "requestType": "open_request"
    })
    .done(function(response) {
      // Unblock the page
      $("html").css("cursor", "auto");
      $("body").css("pointer-events", "auto");

      if (response && response.event === "success") {
        if (response.type && response.type === "cancelled_ticket") {
          if (response.ticket){
            let ticket = response.ticket;
            // Send the ticket to connected support users
            socket.emit('from client', 'client cancelled ticket', ticket);

            // Remove the ticket request from the local list
            window.inQueueTickets = window.inQueueTickets.filter(
              r => r.id_chamado !== ticket.id_chamado
            );

            // Remove the ticket request from the table
            $('form[name=chamados_abertos_clientes]').find(`[data-request-id=${ticket.id_chamado}]`).remove();

            // Hide the modal
            $('#simple-modal').modal('hide');
            return true;
          }
        }
      }
      window.location.reload(true);
    })
    .fail(function(data) {
      // Unblock the page
      $("html").css("cursor", "auto");
      $("body").css("pointer-events", "auto");

      if (data && data.responseJSON) {
        response = data.responseJSON;
        if (response.event && response.type) {
          if (response.event === "error") {
            if (response.type === "missing_data") {
              alert("Há dados fazendo falta");
              $('#simple-modal').modal('hide');
              return false;
            } else if (response.type === "db_op_failed") {
              alert("Não foi possível alterar os dados no banco de dados");
              $('#simple-modal').modal('hide');
              return false;
            }
          }
        }
      }
      alert("Houve uma falha não identificada");
      window.location.reload(true);
    });
  }
  const cancelTicketRequestBtnClick = (e) => {
    let requestId = e.target.value;
    setSimpleModalContent("Cancelar solicitação?", "<h4>Tem certeza que deseja cancelar a solicitação de chamado?</h4>", cancelRequest.bind(null, requestId), "Cancelar solicitação", "Voltar");
    $('#simple-modal').modal('show');
  };
</script>

<!-- Tables handling -->
<script>
  const calculateDeadlineMsg = (deadlineDatetime) => {
    let a = moment();
    let b = moment(deadlineDatetime, "YYYY-MM-DD HH:mm:ss");
    let interval = b.diff(a, 'months');
    let deadlineMsg = "";
    if (interval >= 2 || interval <= -2) {
      // Months of difference
      deadlineMsg = (interval > 0) ? `Daqui a ${interval} meses` : `${Math.abs(interval)} meses atrasado`;
    } else {
      interval = b.diff(a, 'weeks');
      if (interval >= 2 || interval <= -2) {
        // Weeks of difference
        deadlineMsg = (interval > 0) ? `Daqui a ${interval} semanas` : `${Math.abs(interval)} semanas atrasado`;
      } else {
        interval = b.diff(a, 'days');
        if (interval >= 2 || interval <= -2) {
          // Days of difference
          deadlineMsg = (interval > 0) ? `Daqui a ${interval} dias` : `${Math.abs(interval)} dias atrasado`;
        } else {
          interval = b.diff(a, 'hours');
          if (interval >= 24 || interval <= -24) {
            deadlineMsg = (interval > 0) ? `Daqui a 2 dias` : `2 dias atrasado`;
          } else if (a.format("YYYY-MM-DD") === b.format("YYYY-MM-DD")) {
            deadlineMsg = "Hoje";
          } else {
            deadlineMsg = (interval > 0) ? `Daqui a 1 dia` : `1 dia atrasado`;
          }
        }
      }
    }
    return deadlineMsg;
  };

  function insertInProcessingRequestsTable(request) {
    let inProcessRequestsTable = $('#processing-requests');

    // Row structure
    let newRow = $("<tr>").attr("data-request-id", request.id_chamado);
    let cols = "";
    cols += `<td>${request.id_chamado}</td>`;
    cols += `<td>${request.servico}</td>`;
    cols += `<td>${calculateDeadlineMsg(request.prazo)}</td>`
    cols += `<td>${request.tecnico_responsavel}</td>`;
    cols += `<td>${request.tecnico_abertura}</td>`;
    newRow.append(cols);

    // Events
    $(newRow).on('click', clickInProcessRequestTableRow);

    // Add the row to the table
    inProcessRequestsTable.append(newRow);
  }
  function insertInOpenedRequestsTable(request) {
    let openedRequestsTable = $('#not-processing-requests');

    // Row structure
    let newRow = $("<tr>").attr("data-request-id", request.id_chamado);

    let cols = "";
    cols += `<td>${request.id_chamado}</td>`;
    cols += `<td>${request.servico}</td>`;
    cols += `<td>${calculateDeadlineMsg(request.prazo)}</td>`;
    cols += `<td>${request.tecnico_abertura}</td>`;
    newRow.append(cols);

    // Cancel request button
    let btnCancelRequest = $(
      `<button type="button"\
      class="btn btn-primary"\
      name="btnCancelarSolicitacao"\
      value="${request.id_chamado}">Cancelar</button>`);
    newRow.append($("<td>").append(btnCancelRequest));

    // Events
    $(newRow).on('click', clickOpenedRequestTableRow);
    $(btnCancelRequest).on('click', cancelTicketRequestBtnClick);

    // Add the row to the table
    openedRequestsTable.append(newRow);
  }
</script>

<!-- Ready -->
<script>
  const populateInProcessRequestsTable = () => {
    // Take only the requests being processed (status "ATENDIMENTO")
    for (request of window.inProcessTickets) {
      insertInProcessingRequestsTable(request);
    }
  };
  const populateOpenRequestsTable = () => {
    // Take only the accepted requests (status "AGUARDANDO")
    for (request of window.inQueueTickets) {
      insertInOpenedRequestsTable(request);
    }
  };

  $(document).ready(function() {
    //  If user is on tour
    if (window.innerWidth > 980 && sessionStorage.getItem("lastLogin") === null) {
      tour.init();
      tour.start();
      if (localStorage.getItem('tour_current_step') == "8") {
        tour.next();
      }
    }

    // Load the requests for the page
    window.inQueueTickets = <?php echo json_encode($this->view->inQueueTickets) ?>;
    window.inProcessTickets = <?php echo json_encode($this->view->inProcessTickets) ?>;

    // Populate the tables
    populateInProcessRequestsTable();
    populateOpenRequestsTable();
  });
</script>
</body>
