<!-- Layout Dashboard-->
<!-- Bootstrap -->
<link href="../../App/View/css/bootstrap.min.css" rel="stylesheet">
<!-- Font Awesome -->
<link href="../../App/View/css/fontawesome-all.min.css" rel="stylesheet">
<script defer src="../../App/View/js/fontawesome-all.min.js"></script>
<!-- Custom Theme Style -->
<link href="../../App/View/css/custom.min.css" rel="stylesheet">
<link href="../../App/View/css/base-style.css" rel="stylesheet">
<link href="../../App/View/css/custom-style-override.css" rel="stylesheet">
<link href="../../App/View/css/custom-modal.css" rel="stylesheet">
</head>

<body class="nav-md">
  <div class="container body">
    <div class="main_container">

      <div class="col-md-3 left_col">
        <div class="left_col scroll-view">
          <div class="navbar nav_title" style="border: 0;">
            <a href="../cliente" class="site_title"><img src="../../App/View/img/logo.svg" id="sidebar-logo" alt="Logo"><span id="sidebar-logo-text"><span>TI</span> <span>CCHLA</span></span></a>
          </div>

          <div class="clearfix"></div>

          <!-- menu profile quick info -->
          <div class="profile clearfix">
            <div class="profile_pic">
              <img src="" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
              <span>Bem-vindo,</span>
              <h2><?php echo $_SESSION['user_name'];?></h2>
            </div>
          </div>
          <!-- /menu profile quick info -->

          <br />

          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
              <h3></h3>
              <ul class="nav side-menu">
                <li>
                  <a href="../cliente">
                    <span class="fa-layers fa-fw">
                      <i class="fas fa-home"></i>
                    </span> Início
                  </a>
                </li>
                <li>
                  <a href="./solicitar_atendimento">
                    <span class="fa-layers fa-fw">
                      <i class="fas fa-user"></i>
                      <i class="fas fa-wrench" data-fa-transform="shrink-4 down-4.2 right-7" style="color:#2DA7F9;"></i>
                    </span> Solicitar atendimento
                  </a>
                </li>
                <li>
                  <a href="./historico_chamados">
                    <span class="fa-layers fa-fw">
                      <i class="fas fa-list"></i>
                      <i class="fas fa-history  " data-fa-transform="shrink-4 down-12.2 right-9" style="color:#2DA7F9;"></i>
                  </span> Histórico de chamados
                  </a>
                </li>
              </ul>
            </div>

          </div>
          <!-- /sidebar menu -->

          <!-- /menu footer buttons -->
          <!--<div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
              <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
              <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
              <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout" href="logout">
              <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
          </div>-->
          <!-- /menu footer buttons -->
        </div>
      </div>

      <!-- top navigation -->
      <div class="top_nav">
        <div class="nav_menu">
          <nav>
            <div class="nav toggle">
              <a id="menu_toggle"><i class="fas fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
              <li>
                <a href="" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                  <i class="fas fa-user"></i> <?php echo $_SESSION['user_name'];?>
                  <span class="fas fa-angle-down"></span>
                </a>
                <ul class="dropdown-menu dropdown-usermenu pull-right">
                  <li>
                    <a href="./configuracoes" data-original-title="Configurações da conta">
                      <i class="fas fa-wrench pull-right"></i> Configurações da conta
                    </a>
                  </li>
                  <li>
                    <a href="../logout" data-original-title="Sair">
                      <i class="fas fa-sign-out-alt pull-right"></i> Sair
                    </a>
                  </li>
                </ul>
              </li>
            </ul>
          </nav>
        </div>
      </div>
      <!-- /top navigation -->

      <!-- page content -->

      <div class="right_col" role="main">
        <div class="">
          <div class="page-title">
            <div class="title_left" style="margin-bottom:20px;">
              <h3>Histórico dos meus chamados</h3>
            </div>
          </div>
          <div class="clearfix"></div>

          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_content">
                  <form name="form_historico_chamados_cliente" method="post" action="">
                  <table id="closed-requests" class="table table-hover clickable-rows">
                    <thead>
                      <tr>
                        <th>ID</th>
                        <th>Serviço</th>
                        <th>Status</th>
                        <th>Técnico Responsável</th>
                        <th>Técnico Abertura</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php foreach ($this->view->requests as $callrequest):?>
                        <tr data-request-id="<?php echo $callrequest['id'];?>">
                          <a href="view_request">
                            <td><?php echo $callrequest['id']; ?></td>
                            <td><?php echo $this->view->service_names[$callrequest['id_servico']];?></td>
                            <td><?php echo $callrequest['status']; ?></td>
                            <td><?php echo $this->view->user_info[$callrequest['id_tecnico_responsavel']]['nome'];?></td>
                            <td><?php echo $this->view->user_info[$callrequest['id_tecnico_abertura']]['nome'];?></td>
                          </a>
                        </tr>
                      <?php endforeach;?>
                    </tbody>
                  </table>
                </form>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
    </div>
    <!-- /page content -->

    <!-- footer content -->
    <!--<footer>

    </footer>-->
    <!-- /footer content -->
    <!-- SCRIPTS DASHBOARD THEME-->

  </div>

  <!-- REQUEST MODAL -->
  <div class="modal fade request-modal" tabindex="-1" role="dialog"></div>

  <!-- jQuery -->
  <script src="../../App/View/js/jquery.min.js"></script>
  <!-- Bootstrap -->
  <script src="../../App/View/js/bootstrap.min.js"></script>

  <!-- Custom Theme Scripts -->
  <script src="../../App/View/js/custom.min.js"></script>

  <!-- Request modal settings -->
  <script src="../../App/View/js/request-modals.js"></script>
  <script>
  $('#closed-requests tr').on('click', function(e) {
    if (e.target.nodeName == "TR" || e.target.nodeName == "TD") {
      var request_id = getRowId(e);
      if (request_id) {
        modal_config = {
          title: "Detalhes do chamado",
          visible_fields: {
            id_chamado_field: true,
            chamado_status_field: true,
            cliente_field: true,
            servico_field: true,
            data_abertura_field: true,
            tecnico_abertura_field: true,
            descricao_field: true,
            prazo_field: true,
            parecer_tecnico_field: true,
            tecnico_responsavel_field: true
          }
        };
        defineSimpleModal(modal_config, "open-request-type", request_id);
      }
    }
  });
  </script>
</body>
