<!-- Layout Dashboard-->
<!-- Bootstrap -->
<link href="../App/View/css/bootstrap.min.css" rel="stylesheet">
<!-- Bootstrap Tour -->
<link href="../App/View/css/bootstrap-tour.min.css" rel="stylesheet">
<link href="../App/View/css/tour-popover.css" rel="stylesheet">
<!-- Font Awesome -->
<link href="../App/View/css/fontawesome-all.min.css" rel="stylesheet">
<script defer src="../App/View/js/fontawesome-all.min.js"></script>
<!-- NProgress -->
<link href="../App/View/css/nprogress.css" rel="stylesheet">
<!-- iCheck -->
<link href="../App/View/icheck/skins/square/blue.css" rel="stylesheet">
<!-- Custom Theme Style -->
<link href="../App/View/css/custom.min.css" rel="stylesheet">
<link href="../App/View/css/base-style.css" rel="stylesheet">
<link href="../App/View/css/custom-style-override.css" rel="stylesheet">
<link href="../App/View/css/custom-modal.css" rel="stylesheet">
</head>

<body class="nav-md">
<div class="container body">
  <div class="main_container">

    <div class="col-md-3 left_col">
      <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
          <a href="./cliente" class="site_title"><img src="../App/View/img/logo.svg" id="sidebar-logo" alt="Logo"><span id="sidebar-logo-text"><span>TI</span> <span>CCHLA</span></span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
          <div class="profile_pic">
            <img src="" alt="..." class="img-circle profile_img">
          </div>
          <div class="profile_info">
            <span>Bem-vindo,</span>
            <h2><?php echo $_SESSION['user_name'];?></h2>
          </div>
        </div>
        <!-- /menu profile quick info -->

        <br />

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
          <div class="menu_section">
            <h3></h3>
            <ul class="nav side-menu">
              <li>
                <a href="./cliente">
                  <span class="fa-layers fa-fw">
                    <i class="fas fa-home"></i>
                  </span> Início
                </a>
              </li>
              <li>
                <a href="cliente/solicitar_atendimento">
                  <span class="fa-layers fa-fw">
                    <i class="fas fa-user"></i>
                    <i class="fas fa-wrench" data-fa-transform="shrink-4 down-4.2 right-7" style="color:#2DA7F9;"></i>
                  </span> Solicitar atendimento
                </a>
              </li>
              <li>
                <a href="cliente/historico_chamados">
                  <span class="fa-layers fa-fw">
                    <i class="fas fa-list"></i>
                    <i class="fas fa-history  " data-fa-transform="shrink-4 down-12.2 right-9" style="color:#2DA7F9;"></i>
                </span> Histórico de chamados
                </a>
              </li>
            </ul>
          </div>

        </div>
        <!-- /sidebar menu -->

        <!-- /menu footer buttons -->
        <!--<div class="sidebar-footer hidden-small">
          <a data-toggle="tooltip" data-placement="top" title="Settings">
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
          </a>
          <a data-toggle="tooltip" data-placement="top" title="FullScreen">
            <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
          </a>
          <a data-toggle="tooltip" data-placement="top" title="Lock">
            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
          </a>
          <a data-toggle="tooltip" data-placement="top" title="Logout" href="logout">
            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
          </a>
        </div>-->
        <!-- /menu footer buttons -->
      </div>
    </div>

    <!-- top navigation -->
    <div class="top_nav">
      <div class="nav_menu">
        <nav>
          <div class="nav toggle">
            <a id="menu_toggle"><i class="fas fa-bars"></i></a>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <i class="fas fa-user"></i> <?php echo $_SESSION['user_name'];?>
                <span class="fas fa-angle-down"></span>
              </a>
              <ul class="dropdown-menu dropdown-usermenu pull-right">
                <li>
                  <a href="cliente/configuracoes" data-original-title="Configurações da conta">
                    <i class="fas fa-wrench pull-right"></i> Configurações da conta
                  </a>
                </li>
                <li>
                  <a href="logout" data-original-title="Sair">
                    <i class="fas fa-sign-out-alt pull-right"></i> Sair
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </nav>
      </div>
    </div>
    <!-- /top navigation -->

    <!-- page content -->

    <div class="right_col" role="main">
      <div class="">
        <div class="page-title">
          <div class="row tile_count">

          </div>
          <div class="row">
            <div class="col-md-6 col-xs-12">
              <div id="chamados-em-atendimento-panel" class="x_panel">
                <div class="x_title">
                  <h2>CHAMADOS<small>Em atendimento</small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fas fa-angle-up" data-fa-transform="grow-8"></i></a>
                    </li>
                    <!--<li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fas fa-cog"></i></a>
                    </li>-->
                    <!-- <li><a class="close-link"><i class="fas fa-times"></i></a> -->
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <form name="chamados_atendimento_clientes" method="post" action="">
                  <table id="processing-requests" class="table table-hover clickable-rows">
                    <thead>
                      <tr>
                        <th>ID</th>
                        <th>Serviço</th>
                        <th>Status</th>
                        <th>Técnico Responsável</th>
                        <th>Técnico Abertura</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php foreach ($this->view->chamados_atendimento as $callrequest):?>
                        <tr data-request-id="<?php echo $callrequest['id'];?>">
                            <td><?php echo $callrequest['id'];?></td>
                            <td><?php echo $this->view->services_names[$callrequest['id_servico']];?></td>
                            <td><?php echo $callrequest['status'];?></td>
                            <td><?php if($callrequest['status'] == "AGUARDANDO"){
                                        echo " ";
                                      }else{
                                        echo $this->view->users_names[$callrequest['id_tecnico_responsavel']]['nome'];
                                      }?>
                            </td>
                            <td><?php echo $this->view->users_names[$callrequest['id_tecnico_abertura']]['nome'];?></td>
                        </tr>
                      <?php endforeach;?>
                    </tbody>
                  </table>
                </form>
                </div>
              </div>
            </div>
            <div class="col-md-6 col-xs-12">
              <div id="chamados-abertos-panel" class="x_panel">
                <div class="x_title">
                  <h2>CHAMADOS<small>Abertos</small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fas fa-angle-up" data-fa-transform="grow-8"></i></a>
                    </li>
                    <!--<li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fas fa-cog"></i></a>
                    </li>-->
                    <!-- <li><a class="close-link"><i class="fas fa-times"></i></a> -->
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <form name="chamados_abertos_clientes" method="post" action="">
                  <table id="not-processing-requests" class="table table-hover  clickable-rows">
                    <thead>
                      <tr>
                        <th></th>
                        <th>ID</th>
                        <th>Serviço</th>
                        <th>Status</th>
                        <th>Técnico Abertura</th>
                        <th>Ação</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php foreach ($this->view->chamados_abertos as $callrequest):?>
                        <tr data-request-id="<?php echo $callrequest['id'];?>">
                          <td><input type="checkbox" value=<?php echo $callrequest['id'];?> name="selections[]"/></td>
                            <td><?php echo $callrequest['id']; ?></td>
                            <td><?php echo $this->view->services_names[$callrequest['id_servico']];?></td>
                            <td><?php echo $callrequest['status'];?></td>
                            <td><?php echo $this->view->users_names[$callrequest['id_tecnico_abertura']]['nome'];?></td>
                            <td><button type="button" class="btn btn-primary" name="btnCancelarSolicitacao" value=<?php echo $callrequest['id'];?>>Cancelar</button></td>
                        </tr>
                      <?php endforeach;?>
                    </tbody>
                  </table>
                  <button name="cancel-selected-requests" type="button" class="btn btn-default" disabled>Cancelar os selecionados</button>
                </form>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
    </div>
    <!-- /page content -->

    <!-- footer content -->
    <!--<footer>

    </footer>-->
    <!-- /footer content -->
    <!-- SCRIPTS DASHBOARD THEME-->

  </div>

  <!-- REQUEST MODAL -->
  <div class="modal fade request-modal" tabindex="-1" role="dialog"></div>
</div>
<!-- jQuery -->
<script src="../App/View/js/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="../App/View/js/bootstrap.min.js"></script>
<!-- Bootstrap Tour -->
<script src="../App/View/js/bootstrap-tour.min.js"></script>
<script src="../App/View/js/cliente-tour.js"></script>
<script>
$(document).ready(function() {
  if (window.innerWidth > 980 && sessionStorage.getItem("lastLogin") === null) {
    tour.init();
    tour.start();
    if (localStorage.getItem('tour_current_step') == "8") {
      tour.next();
    }
  }
});
</script>
<!-- FastClick -->
<script src="../App/View/js/fastclick.js"></script>
<!-- NProgress -->
<script src="../App/View/js/nprogress.js"></script>
<!-- iCheck -->
<script src="../App/View/js/icheck.min.js"></script>
<script>
$(document).ready(function(){
  $('input').iCheck({
    checkboxClass: 'icheckbox_square-blue',
    radioClass: 'iradio_square'
  });
});
</script>
<!-- Moment.js -->
<script src="../App/View/js/moment.min.js"></script>

<!-- Custom Theme Scripts -->
<script src="../App/View/js/custom.min.js"></script>

<!-- Request modal settings -->
<script src="../App/View/js/request-modals.js"></script>
<script>
$('#processing-requests tr').on('click', function(e) {
  if (e.target.nodeName == "TR" || e.target.nodeName == "TD") {
    var request_id = getRowId(e);
    if (request_id) {
      modal_config = {
        title: "Detalhes do chamado",
        visible_fields: {
          id_chamado_field: true,
          local_field: true,
          chamado_status_field: true,
          servico_field: true,
          data_abertura_field: true,
          tecnico_abertura_field: true,
          descricao_field: true,
          prazo_field: true,
          tecnico_responsavel_field: true
        }
      };
      defineSimpleModal(modal_config, "open-request-type", request_id);
    }
  }
});
$('#not-processing-requests tr').on('click', function(e) {
  if (e.target.nodeName == "TR" || e.target.nodeName == "TD") {
    var request_id = getRowId(e);
    if (request_id) {
      modal_config = {
        title: "Detalhes do chamado",
        visible_fields: {
          id_chamado_field: true,
          local_field: true,
          chamado_status_field: true,
          servico_field: true,
          data_abertura_field: true,
          tecnico_abertura_field: true,
          descricao_field: true,
          prazo_field: true
        }
      };
      defineSimpleModal(modal_config, "open-request-type", request_id);
    }
  }
});
</script>

<!-- Simple message modal -->
<div class="modal fade" id="simple-modal" tabindex="-1" role="dialog" data-backdrop="false">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="simple-modal-title">Modal title</h4>
      </div>
      <div class="modal-body" id="simple-modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button id="simple-modal-secondary-button" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button id="simple-modal-primary-button" type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<script>
function setSimpleModalContent(title, body, primaryButtonAction, primaryButtonText = "Confirmar", secondaryButtonText = "Cancelar") {
  $('#simple-modal-title')[0].innerHTML = title;
  $('#simple-modal-body')[0].innerHTML = body;
  $('#simple-modal-primary-button')[0].innerHTML = primaryButtonText;
  $('#simple-modal-primary-button').off('click');
  $('#simple-modal-primary-button').on('click', primaryButtonAction);
  $('#simple-modal-secondary-button')[0].innerHTML = secondaryButtonText;
}
</script>

<!-- Archive request confirmation -->
<script>
$('#not-processing-requests button[name=btnCancelarSolicitacao]').on('click', function(e) {
  var request_id = [e.target.value];
  var confirm_action = function () {
    $.post("/gticchla/public/cliente/client_cancel_call_request", {
      "request_id_list": request_id,
      "requestType": "open_request"
    })
    .done(function() {
      $('#simple-modal').modal('hide');
      document.location.reload(true);
    })
    .fail(function() {
      alert("Não foi possível realizar a operação");
    });
  };
  setSimpleModalContent("Cancelar solicitação?", "<h4>Tem certeza que deseja cancelar a solicitação de chamado?</h4>", confirm_action, "Cancelar solicitação", "Voltar");
  $('#simple-modal').modal('show');
});
$('form[name=chamados_abertos_clientes] > button[name=cancel-selected-requests]').on('click', function(e) {
  var id_array = [];
  $('form[name=chamados_abertos_clientes]').find('input[type=checkbox]').each(function(){
    if (this.checked) {
      id_array.push(this.value);
    }
  });
  var confirm_action = function () {
    $.post("/gticchla/public/cliente/client_cancel_call_request", {
      "request_id_list": id_array,
      "requestType": "open_request"
    })
    .done(function() {
      $('#simple-modal').modal('hide');
      document.location.reload(true);
    })
    .fail(function() {
      alert("Não foi possível realizar a operação");
    });
  };
  setSimpleModalContent("Cancelar solicitações selecionadas?", "<h4>Tem certeza que deseja cancelar as solicitações de chamado selecionadas?</h4>", confirm_action, "Cancelar solicitações selecionadas", "Voltar");
  $('#simple-modal').modal('show');
});
</script>

<!-- Check if there's request checked -->
<script>

var btn_del_request = $('form[name=chamados_abertos_clientes] > button[name=cancel-selected-requests]');

$('form[name=chamados_abertos_clientes] input').on('ifChecked', function(event) {
  if (btn_del_request.hasClass('btn-default')) {
    btn_del_request.toggleClass('btn-default btn-primary');
    btn_del_request.prop('disabled', function(i, v) { return !v; });
  }
});

$('form[name=chamados_abertos_clientes] input').on('ifUnchecked', function(event) {
  var all_unchecked = true;
  var form_inputs = $('form[name=chamados_abertos_clientes] input[type=checkbox]');

  form_inputs.each(function() {
    if (this.checked) {
      all_unchecked = false;
    }
  });

  if (all_unchecked) {
    btn_del_request.toggleClass('btn-default btn-primary');
    btn_del_request.prop('disabled', function(i, v) { return !v; });
  }
});
</script>
</body>
