<!-- Layout Dashboard-->
<!-- Bootstrap -->
<link href="../App/View/css/bootstrap.min.css" rel="stylesheet">
<!-- Font Awesome -->
<link href="../App/View/css/font-awesome.min.css" rel="stylesheet">
<!-- NProgress -->
<link href="../App/View/css/nprogress.css" rel="stylesheet">
<!-- iCheck -->
<link href="../App/View/css/green.css" rel="stylesheet">
<!-- Custom Theme Style -->
<link href="../App/View/css/custom.min.css" rel="stylesheet">
</head>

<body class="nav-md">
<div class="container body">
  <div class="main_container">

    <div class="col-md-3 left_col">
      <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
          <a href="index.html" class="site_title"><img src="../App/View/img/gsolo.png" alt="..."> <span>TI CCHLA</span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
          <div class="profile_pic">
            <img src="" alt="..." class="img-circle profile_img">
          </div>
          <div class="profile_info">
            <span>Welcome,</span>
            <h2><?php echo $_SESSION['user_name'];?></h2>
          </div>
        </div>
        <!-- /menu profile quick info -->

        <br />

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
          <div class="menu_section">
            <h3></h3>
            <ul class="nav side-menu">
              <li><a href="cliente/solicitar_atendimento"><i class="fa fa-table"></i> Solicitar atendimento <span class="fa fa-chevron-down"></span></a>

              </li>

            </ul>
          </div>

        </div>
        <!-- /sidebar menu -->

        <!-- /menu footer buttons -->
        <div class="sidebar-footer hidden-small">
          <a data-toggle="tooltip" data-placement="top" title="Settings">
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
          </a>
          <a data-toggle="tooltip" data-placement="top" title="FullScreen">
            <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
          </a>
          <a data-toggle="tooltip" data-placement="top" title="Lock">
            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
          </a>
          <a data-toggle="tooltip" data-placement="top" title="Logout" href="logout">
            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
          </a>
        </div>
        <!-- /menu footer buttons -->
      </div>
    </div>

    <!-- top navigation -->
    <div class="top_nav">
      <div class="nav_menu">
        <nav>
          <div class="nav toggle">
            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
          </div>

          <ul class="nav navbar-nav navbar-right">

          </ul>
        </nav>
      </div>
    </div>
    <!-- /top navigation -->

    <!-- page content -->

    <div class="right_col" role="main">
      <div class="">
        <div class="page-title">
          <div class="row tile_count">

          </div>
          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>Chamado <small>Detalhe</small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                      <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Settings 1</a>
                        </li>
                        <li><a href="#">Settings 2</a>
                        </li>
                      </ul>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">

                  <form class="form-horizontal form-label-left" novalidate>
                    <div class="item form-group">
                      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="textarea">Cliente <span class="required">:</span>
                      </label>
                      <div class="col-md-6 col-sm-6 col-xs-12">
                        <textarea id="text_client" required="required" readonly="readonly" name="text_client" class="form-control col-md-7 col-xs-12" ><?php echo $this->view->users[$this->view->request['id_cliente_solicitante']]['nome'];?></textarea>
                      </div>
                    </div>
                    <div class="item form-group">
                      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="textarea">Serviço <span class="required">:</span>
                      </label>
                      <div class="col-md-6 col-sm-6 col-xs-12">
                        <textarea id="text_servico" required="required" readonly="readonly" name="text_servico" class="form-control col-md-7 col-xs-12" ><?php echo $this->view->services[$this->view->request['id_servico']];?></textarea>
                      </div>
                    </div>
                    <div class="item form-group">
                      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="occupation">Data abertura <span class="required">:</span>
                      </label>
                      <div class="col-md-6 col-sm-6 col-xs-12">
                        <input value=<?php echo $this->view->request['data_abertura'];?> id="occupation" type="text" name="text_date" data-validate-length-range="5,20" class="optional form-control col-md-7 col-xs-12">
                      </div>
                    </div>
                    <div class="item form-group">
                      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="textarea">Técnico abertura <span class="required">:</span>
                      </label>
                      <div class="col-md-6 col-sm-6 col-xs-12">
                        <textarea id="text_technician" required="required" readonly="readonly" name="text_technician" class="form-control col-md-7 col-xs-12" ><?php echo $this->view->users[$this->view->request['id_tecnico_abertura']]['nome'];?></textarea>
                      </div>
                    </div>
                    <div class="item form-group">
                      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="textarea">Descrição <span class="required">:</span>
                      </label>
                      <div class="col-md-6 col-sm-6 col-xs-12">
                        <textarea id="text_description" required="required" readonly="readonly" name="text_description" class="form-control col-md-7 col-xs-12" ><?php echo $this->view->request['descricao'];?></textarea>
                      </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                      <div class="col-md-6 col-md-offset-3">
                        <button type="submit" class="btn btn-primary">Back</button>
                        <button id="send" type="submit" class="btn btn-success">Join</button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /page content -->

    <!-- footer content -->
    <footer>

    </footer>
    <!-- /footer content -->
    <!-- SCRIPTS DASHBOARD THEME-->

  </div>
</div>
<!-- jQuery -->
<script src="../App/View/js/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="../App/View/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="../App/View/js/fastclick.js"></script>
<!-- NProgress -->
<script src="../App/View/js/nprogress.js"></script>
<!-- iCheck -->
<script src="../App/View/js/icheck.min.js"></script>

<!-- Custom Theme Scripts -->
<script src="../App/View/js/custom.min.js"></script>
</body>
