<!-- Layout Dashboard-->
<!-- Bootstrap -->
<link href="../App/View/css/bootstrap.min.css" rel="stylesheet">
<!-- Font Awesome -->
<link href="../App/View/css/fontawesome-all.min.css" rel="stylesheet">
<script defer src="../App/View/js/fontawesome-all.min.js"></script>
<!-- NProgress -->
<link href="../App/View/css/nprogress.css" rel="stylesheet">
<!-- iCheck -->
<link href="../App/View/css/green.css" rel="stylesheet">
<!-- Custom Theme Style -->
<link href="../App/View/css/custom.min.css" rel="stylesheet">
<link href="../App/View/css/base-style.css" rel="stylesheet">
<link href="../App/View/css/custom-style-override.css" rel="stylesheet">
</head>

<body class="nav-md">
<div class="container body">
  <div class="main_container">

    <!-- top navigation -->
    <div class="top_nav" style="margin-left: 0;">
      <div class="nav_menu">
        <nav>
          <div class="nav toggle">
            <a href="./tecnico" style="display:block;width:210px;font-size:1.8em;font-weight:900;padding:2px 20px;"><img src="../App/View/img/logo.svg" id="sidebar-logo" alt="Logo"><span id="sidebar-logo-text" style="top:3px;"><span>TI</span> <span>CCHLA</span></span></a>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <i class="fas fa-user"></i> <?php echo $_SESSION['user_name'];?>
                <span class="fas fa-angle-down"></span>
              </a>
              <ul class="dropdown-menu dropdown-usermenu pull-right">
                <li>
                  <a href="logout" data-original-title="Sair">
                    <i class="fas fa-sign-out-alt pull-right"></i> Sair
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </nav>
      </div>
    </div>
    <!-- /top navigation -->

    <!-- page content -->

    <div class="right_col" style="margin-left: 0;" role="main">
      <div class="">
        <div class="page-title">
          <div class="row tile_count">

          </div>
          <div class="row">
            <div class="col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>CHAMADO <small>Detalhe</small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fas fa-angle-up" data-fa-transform="grow-8"></i></a>
                    </li>
                    <!--<li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fas fa-cog"></i></a>
                      <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Settings 1</a>
                        </li>
                        <li><a href="#">Settings 2</a>
                        </li>
                      </ul>
                    </li>-->
                    <!-- <li><a class="close-link"><i class="fas fa-times"></i></a> -->
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">

                  <form class="form-horizontal form-label-left" novalidate method="post" action="technician_select_request">
                    <div class="item form-group">
                      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="textarea">Cliente <span class="required">:</span>
                      </label>
                      <div class="col-md-6 col-sm-6 col-xs-12">
                        <textarea id="text_client" required="required" readonly="readonly" name="text_client" class="form-control col-md-7 col-xs-12" ><?php echo $this->view->users[$this->view->request['id_cliente_solicitante']]['nome'];?></textarea>
                      </div>
                    </div>
                    <div class="item form-group">
                      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="textarea">Serviço <span class="required">:</span>
                      </label>
                      <div class="col-md-6 col-sm-6 col-xs-12">
                        <textarea id="text_servico" required="required" readonly="readonly" name="text_servico" class="form-control col-md-7 col-xs-12" ><?php echo $this->view->services[$this->view->request['id_servico']];?></textarea>
                      </div>
                    </div>
                    <div class="item form-group">
                      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="occupation">Data abertura <span class="required">:</span>
                      </label>
                      <div class="col-md-6 col-sm-6 col-xs-12">
                        <input value=<?php echo $this->view->request['data_abertura'];?> id="occupation" type="text" name="text_date" data-validate-length-range="5,20" class="optional form-control col-md-7 col-xs-12">
                      </div>
                    </div>
                    <div class="item form-group">
                      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="textarea">Técnico abertura <span class="required">:</span>
                      </label>
                      <div class="col-md-6 col-sm-6 col-xs-12">
                        <textarea id="text_technician" required="required" readonly="readonly" name="text_technician" class="form-control col-md-7 col-xs-12" ><?php echo $this->view->users[$this->view->request['id_tecnico_abertura']]['nome'];?></textarea>
                      </div>
                    </div>
                    <div class="item form-group">
                      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="textarea">Descrição <span class="required">:</span>
                      </label>
                      <div class="col-md-6 col-sm-6 col-xs-12">
                        <textarea id="text_description" required="required" readonly="readonly" name="text_description" class="form-control col-md-7 col-xs-12" ><?php echo $this->view->request['descricao'];?></textarea>
                      </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                      <div class="col-md-6 col-md-offset-3">
                        <a href="./tecnico" class="btn btn-primary">Voltar</a>
                        <button type="submit" class="btn btn-primary" name="btnJoin" value=<?php echo $this->view->request['id'];?>>Join</button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /page content -->

    <!-- footer content -->
    <!--<footer>

    </footer>-->
    <!-- /footer content -->
    <!-- SCRIPTS DASHBOARD THEME-->

  </div>
</div>
<!-- jQuery -->
<script src="../App/View/js/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="../App/View/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="../App/View/js/fastclick.js"></script>
<!-- NProgress -->
<script src="../App/View/js/nprogress.js"></script>
<!-- iCheck -->
<script src="../App/View/js/icheck.min.js"></script>

<!-- Custom Theme Scripts -->
<script src="../App/View/js/custom.min.js"></script>
</body>
