<!-- Layout Dashboard-->
<!-- Bootstrap -->
<link href="../App/View/css/bootstrap.min.css" rel="stylesheet">
<!-- Font Awesome -->
<link href="../App/View/css/fontawesome-all.min.css" rel="stylesheet">
<script defer src="../App/View/js/fontawesome-all.min.js"></script>
<!-- NProgress -->
<link href="../App/View/css/nprogress.css" rel="stylesheet">
<!-- iCheck -->
<link href="../App/View/icheck/skins/square/blue.css" rel="stylesheet">
<!-- Custom Theme Style -->
<link href="../App/View/css/custom.min.css" rel="stylesheet">
<link href="../App/View/css/base-style.css" rel="stylesheet">
<link href="../App/View/css/custom-style-override.css" rel="stylesheet">
<link href="../App/View/css/custom-modal.css" rel="stylesheet">
</head>

<body class="nav-md">
<div class="container body">
  <div class="main_container">

    <!-- top navigation -->
    <div class="top_nav" style="margin-left: 0;">
      <div class="nav_menu">
        <nav>
          <div class="nav toggle">
            <a href="./tecnico" style="display:block;width:210px;font-size:1.8em;font-weight:900;padding:2px 20px;"><img src="../App/View/img/logo.svg" id="sidebar-logo" alt="Logo"><span id="sidebar-logo-text" style="top:3px;"><span>TI</span> <span>CCHLA</span></span></a>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <i class="fas fa-user"></i> <?php echo $_SESSION['user_name'];?>
                <span class="fas fa-angle-down"></span>
              </a>
              <ul class="dropdown-menu dropdown-usermenu pull-right">
                <li>
                  <a href="logout" data-original-title="Sair">
                    <i class="fas fa-sign-out-alt pull-right"></i> Sair
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </nav>
      </div>
    </div>
    <!-- /top navigation -->

    <!-- page content -->

    <div class="right_col" role="main" style="margin-left: 0;">
      <div class="">
        <div class="page-title">
          <div class="row tile_count">

          </div>
          <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>MEUS SERVIÇOS<small>Em atendimento</small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fas fa-angle-up" data-fa-transform="grow-8"></i></a>
                    </li>
                    <!--<li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fas fa-cog"></i></a>
                    </li>-->
                    <!--<li><a class="close-link"><i class="fas fa-times"></i></a>
                    </li>-->
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <form name="meus_servicos_atendimento_form">
                  <table class="table table-hover open-request-list">
                    <thead>
                      <tr>
                        <th>ID</th>
                        <th>Cliente</th>
                        <th>Serviço</th>
                        <th>Prazo</th>
                        <th>Técnico Responsável</th>
                        <th>Ação</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php foreach ($this->view->myRequests as $callrequest):?>
                        <tr>
                          <a href="view_request">
                            <td><?php echo $callrequest['id_solicitacao']; ?></td>
                            <td><?php echo $this->view->users_names[$callrequest['id_cliente_solicitante']]['nome'];?></td>
                            <td><?php echo $this->view->service_names[$callrequest['id_servico']];?></td>
                            <td><?php echo $callrequest['prazo']; ?></td>
                            <td><?php echo $this->view->users_names[$callrequest['id_tecnico_responsavel']]['nome'];?></td>
                            <td><button type="button" class="btn btn-primary" name="btnFinalizarChamado" value=<?php echo $callrequest['id_solicitacao'];?>>Finalizar</button></td>
                          </a>
                        </tr>
                      <?php endforeach;?>
                    </tbody>
                  </table>
                </form>
                </div>
              </div>
              <div class="x_panel">
                <div class="x_title">
                  <h2>CHAMADOS<small>Abertos</small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fas fa-angle-up" data-fa-transform="grow-8"></i></a>
                    </li>
                    <!--<li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fas fa-cog"></i></a>
                    </li>-->
                    <!-- <li><a class="close-link"><i class="fas fa-times"></i></a> -->
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <form name="chamados_clientes" method="post" action="technician_select_request">
                  <table class="table table-hover open-request-list">
                    <thead>
                      <tr>
                        <th>ID</th>
                        <th>Cliente</th>
                        <th>Serviço</th>
                        <th>Setor</th>
                        <th>Técnico Abertura</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php foreach ($this->view->openRequests as $callrequest):?>
                        <tr>
                          <td><?php echo $callrequest['id_solicitacao']; ?></td>
                          <td><?php echo $this->view->users_names[$callrequest['id_cliente_solicitante']]['nome'];?></td>
                          <td><?php echo $this->view->service_names[$callrequest['id_servico']];?></td>
                          <td><?php echo $this->view->users_names[$callrequest['id_cliente_solicitante']]['setor'];?></td>
                          <td><?php echo $this->view->users_names[$callrequest['id_tecnico_abertura']]['nome'];?></td>
                          <td><button type="submit" class="btn btn-primary" name="btnDetail" value=<?php echo $callrequest['id'];?>>Ver</button></td>
                          <td><button type="submit" class="btn btn-primary" name="btnJoin" value=<?php echo $callrequest['id'];?>>Join</button></td>
                        </tr>
                      <?php endforeach;?>
                    </tbody>
                  </table>
                </form>
                </div>
              </div>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>SOLICITAÇÕES<small>de serviço</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fas fa-angle-up" data-fa-transform="grow-8"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <form name="solicitacoes_chamados" method="post" action="admin/open_call_request">
                            <table class="table table-hover call-request-list">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Cliente</th>
                                        <th>Serviço</th>
                                        <th>Setor</th>
                                        <th>Descrição</th>
                                        <th>Ação</th>
                                    </tr>
                                </thead>
                                <tbody>
                                  <?php foreach ($this->view->requisicoes_atendimento as $call_request): ?>
                                    <tr>
                                        <td><?php echo $call_request['id']; ?></td>
                                        <td><?php echo $this->view->users_names[$call_request['id_cliente']]['nome'];?></td>
                                        <td><?php echo $this->view->service_names[$call_request['id_servico']];?></td>
                                        <td><?php echo $this->view->users_names[$call_request['id_cliente']]['setor'];?></td>
                                        <td><?php echo $call_request['descricao'];?></td>
                                        <td> <input type="checkbox" value=<?php echo $call_request['id'];?> name="selections_call_request[]"/></td>
                                    </tr>
                                  <?php endforeach; ?>
                                </tbody>
                            </table>
                            <input type="hidden" name="admin_open_client_call_request" value="admin_open_client_call_request"/>
                            <button type="submit" class="btn btn-default" value="open-request" disabled>Abrir Chamado</button>
                        </form>
                    </div>
                </div>
                <div class="x_panel">
                  <div class="x_title">
                    <h2>CHAMADOS<small>Em atendimento</small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fas fa-angle-up" data-fa-transform="grow-8"></i></a>
                      </li>
                      <!--<li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fas fa-cog"></i></a>
                      </li>-->
                      <!--<li><a class="close-link"><i class="fas fa-times"></i></a>
                      </li>-->
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <form name="chamados_clientes">
                    <table class="table table-hover open-request-list">
                      <thead>
                        <tr>
                          <th>ID</th>
                          <th>Cliente</th>
                          <th>Serviço</th>
                          <th>Prazo</th>
                          <th>Técnico Responsável</th>
                        </tr>
                      </thead>
                      <tbody>
                        <?php foreach ($this->view->requests_attendance as $callrequest):?>
                          <tr>
                            <a href="view_request">
                              <td><?php echo $callrequest['id_solicitacao']; ?></td>
                              <td><?php echo $this->view->users_names[$callrequest['id_cliente_solicitante']]['nome'];?></td>
                              <td><?php echo $this->view->service_names[$callrequest['id_servico']];?></td>
                              <td><?php echo $callrequest['prazo']; ?></td>
                              <td><?php echo $this->view->users_names[$callrequest['id_tecnico_responsavel']]['nome'];?></td>
                            </a>
                          </tr>
                        <?php endforeach;?>
                      </tbody>
                    </table>
                  </form>
                  </div>
                </div>
            </div>

            <div class="clearfix"></div>
          </div>
          <!-- <div class="row"> -->

          <!-- </div> -->
        </div>
      </div>
    </div>
    <!-- /page content -->

    <!-- footer content -->
    <!--<footer>

    </footer>-->
    <!-- /footer content -->
    <!-- SCRIPTS DASHBOARD THEME-->

  </div>

  <!-- REQUEST MODAL -->
   <div class="modal fade request-modal" tabindex="-1" role="dialog">
     <div class="modal-dialog" role="document">
       <div class="modal-content">
         <div class="modal-header">
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
           <h4 class="modal-title"></h4>
         </div>
         <div class="modal-body">
           <form class="form-horizontal request-modal-form">
             <div class="form-group" style="display: none;">
               <label for="id_solicitacao_field" class="col-sm-4 control-label">Solicitação</label>
               <div class="col-sm-8">
                 <input type="text" class="form-control" id="id_solicitacao_field" readonly>
               </div>
             </div>
             <div class="form-group" style="display: none;">
               <label for="solicitacao_chamado_status_field" class="col-sm-4 control-label">Status</label>
               <div class="col-sm-8">
                 <input type="text" class="form-control" id="solicitacao_chamado_status_field" readonly>
               </div>
             </div>
             <div class="form-group" style="display: none;">
               <label for="chamado_status_field" class="col-sm-4 control-label">Status</label>
               <div class="col-sm-8">
                 <input type="text" class="form-control" id="chamado_status_field" readonly>
               </div>
             </div>
             <div class="form-group" style="display: none;">
               <label for="servico_field" class="col-sm-4 control-label">Serviço</label>
               <div class="col-sm-8">
                 <input type="text" class="form-control" id="servico_field" readonly>
               </div>
             </div>
             <div class="form-group" style="display: none;">
               <label for="cliente_field" class="col-sm-4 control-label">Cliente</label>
               <div class="col-sm-8">
                 <input type="text" class="form-control" id="cliente_field" readonly>
               </div>
             </div>
             <div class="form-group" style="display: none;">
               <label for="data_solicitacao_field" class="col-sm-4 control-label">Data da solicitação</label>
               <div class="col-sm-8">
                 <input type="text" class="form-control" id="data_solicitacao_field" readonly>
               </div>
             </div>
             <div class="form-group" style="display: none;">
               <label for="data_abertura_field" class="col-sm-4 control-label">Data de abertura</label>
               <div class="col-sm-8">
                 <input type="text" class="form-control" id="data_abertura_field" readonly>
               </div>
             </div>
             <div class="form-group" style="display: none;">
               <label for="data_finalizado_field" class="col-sm-4 control-label">Data finalizado</label>
               <div class="col-sm-8">
                 <input type="text" class="form-control" id="data_finalizado_field" readonly>
               </div>
             </div>
             <div class="form-group" style="display: none;">
               <label for="prazo_field" class="col-sm-4 control-label">Prazo</label>
               <div class="col-sm-8">
                 <input type="text" class="form-control" id="prazo_field" readonly>
               </div>
             </div>
             <div class="form-group" style="display: none;">
               <label for="tecnico_responsavel_field" class="col-sm-4 control-label">Técnico responsável</label>
               <div class="col-sm-8">
                 <input type="text" class="form-control" id="tecnico_responsavel_field" readonly>
               </div>
             </div>
             <div class="form-group" style="display: none;">
               <label for="tecnico_abertura_field" class="col-sm-4 control-label">Técnico da abertura</label>
               <div class="col-sm-8">
                 <input type="text" class="form-control" id="tecnico_abertura_field" readonly>
               </div>
             </div>
             <div class="form-group" style="display: none;">
               <label for="descricao_field" class="col-sm-4 control-label">Descrição</label>
               <div class="col-sm-8">
                 <textarea class="form-control" rows="3" id="descricao_field" readonly></textarea>
               </div>
             </div>
             <div class="form-group" style="display: none;">
               <label for="parecer_tecnico_field" class="col-sm-4 control-label">Parecer técnico</label>
               <div class="col-sm-8">
                 <textarea class="form-control" rows="3" id="parecer_tecnico_field" readonly></textarea>
               </div>
             </div>
           </form>
         </div>
         <div class="modal-footer" style="display: none;"></div>
       </div><!-- /.modal-content -->
     </div><!-- /.modal-dialog -->
   </div><!-- /.modal -->
</div>
<!-- jQuery -->
<script src="../App/View/js/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="../App/View/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="../App/View/js/fastclick.js"></script>
<!-- NProgress -->
<script src="../App/View/js/nprogress.js"></script>
<!-- iCheck -->
<script src="../App/View/js/icheck.min.js"></script>
<script>
$(document).ready(function(){
   $('input').iCheck({
     checkboxClass: 'icheckbox_square-blue',
     radioClass: 'iradio_square'
   });
 });
</script>

<!-- Custom Theme Scripts -->
<script src="../App/View/js/custom.min.js"></script>
<script src="../App/View/js/request-modals.js"></script>

<!-- Check if there is any demand selected -->
<script>
 var btn_abrir_chamado = $('form[name=solicitacoes_chamados] > button[type=submit]');
$('form[name=solicitacoes_chamados] input').on('ifChecked', function(event) {
   if (btn_abrir_chamado.hasClass('btn-default')) {
       btn_abrir_chamado.toggleClass('btn-default btn-primary');
       btn_abrir_chamado.prop('disabled', function(i, v) { return !v; });
   }
});
$('form[name=solicitacoes_chamados] input').on('ifUnchecked', function(event) {
 var all_unchecked = true;
 var form_inputs = $('form[name=solicitacoes_chamados] > table td input[type=checkbox]');
 form_inputs.each(function() {
   if (this.checked){
     all_unchecked = false;
   }
 });
 if (all_unchecked) {
   btn_abrir_chamado.toggleClass('btn-default btn-primary');
   btn_abrir_chamado.prop('disabled', function(i, v) { return !v; });
 }
});
</script>
</body>
