<!-- Layout Dashboard-->
<!-- Bootstrap -->
<link href="../App/View/css/bootstrap.min.css" rel="stylesheet">
<!-- Font Awesome -->
<link href="../App/View/css/fontawesome-all.min.css" rel="stylesheet">
<script defer src="../App/View/js/fontawesome-all.min.js"></script>
<!-- NProgress -->
<link href="../App/View/css/nprogress.css" rel="stylesheet">
<!-- iCheck -->
<link href="../App/View/css/green.css" rel="stylesheet">
<!-- Custom Theme Style -->
<link href="../App/View/css/custom.min.css" rel="stylesheet">
<link href="../App/View/css/base-style.css" rel="stylesheet">
<link href="../App/View/css/custom-style-override.css" rel="stylesheet">
</head>

<body class="nav-md">
<div class="container body">
  <div class="main_container">

    <!-- top navigation -->
    <div class="top_nav" style="margin-left: 0;">
      <div class="nav_menu">
        <nav>
          <div class="nav toggle">
            <a href="./tecnico" style="display:block;width:210px;font-size:1.8em;font-weight:900;padding:2px 20px;"><img src="../App/View/img/logo.svg" id="sidebar-logo" alt="Logo"><span id="sidebar-logo-text" style="top:3px;"><span>TI</span> <span>CCHLA</span></span></a>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <i class="fas fa-user"></i> <?php echo $_SESSION['user_name'];?>
                <span class="fas fa-angle-down"></span>
              </a>
              <ul class="dropdown-menu dropdown-usermenu pull-right">
                <li>
                  <a href="logout" data-original-title="Sair">
                    <i class="fas fa-sign-out-alt pull-right"></i> Sair
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </nav>
      </div>
    </div>
    <!-- /top navigation -->

    <!-- page content -->

    <div class="right_col" role="main" style="margin-left: 0;">
      <div class="">
        <div class="page-title">
          <div class="row tile_count">

          </div>
          <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>CHAMADOS<small>Em atendimento</small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fas fa-angle-up" data-fa-transform="grow-8"></i></a>
                    </li>
                    <!--<li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fas fa-cog"></i></a>
                    </li>-->
                    <li><a class="close-link"><i class="fas fa-times"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <form name="chamados_clientes">
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>Cliente</th>
                        <th>Serviço</th>
                        <th>Prazo</th>
                        <th>Técnico Abertura</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php foreach ($this->view->myRequests as $callrequest):?>
                        <tr>
                          <a href="view_request">
                            <td><?php echo $this->view->users_names[$callrequest['id_cliente_solicitante']]['nome'];?></td>
                            <td><?php echo $this->view->service_names[$callrequest['id_servico']];?></td>
                            <td></td>
                            <td><?php echo $this->view->users_names[$callrequest['id_tecnico_abertura']]['nome'];?></td>
                          </a>
                        </tr>
                      <?php endforeach;?>
                    </tbody>
                  </table>
                </form>
                </div>
              </div>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>CHAMADOS<small>Abertos</small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fas fa-angle-up" data-fa-transform="grow-8"></i></a>
                    </li>
                    <!--<li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fas fa-cog"></i></a>
                    </li>-->
                    <li><a class="close-link"><i class="fas fa-times"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <form name="chamados_clientes" method="post" action="technician_select_request">
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>Cliente</th>
                        <th>Serviço</th>
                        <th>Setor</th>
                        <th>Técnico Abertura</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php foreach ($this->view->openRequests as $callrequest):?>
                        <tr>
                          <td><?php echo $this->view->users_names[$callrequest['id_cliente_solicitante']]['nome'];?></td>
                          <td><?php echo $this->view->service_names[$callrequest['id_servico']];?></td>
                          <td><?php echo $this->view->users_names[$callrequest['id_cliente_solicitante']]['setor'];?></td>
                          <td><?php echo $this->view->users_names[$callrequest['id_tecnico_abertura']]['nome'];?></td>
                          <td><button type="submit" class="btn btn-primary" name="btnDetail" value=<?php echo $callrequest['id'];?>>Ver</button></td>
                          <td><button type="submit" class="btn btn-primary" name="btnJoin" value=<?php echo $callrequest['id'];?>>Join</button></td>
                        </tr>
                      <?php endforeach;?>
                    </tbody>
                  </table>
                </form>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
    </div>
    <!-- /page content -->

    <!-- footer content -->
    <!--<footer>

    </footer>-->
    <!-- /footer content -->
    <!-- SCRIPTS DASHBOARD THEME-->

  </div>
</div>
<!-- jQuery -->
<script src="../App/View/js/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="../App/View/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="../App/View/js/fastclick.js"></script>
<!-- NProgress -->
<script src="../App/View/js/nprogress.js"></script>
<!-- iCheck -->
<script src="../App/View/js/icheck.min.js"></script>

<!-- Custom Theme Scripts -->
<script src="../App/View/js/custom.min.js"></script>
</body>
