<!-- Layout Dashboard-->
<!-- Bootstrap -->
<link href="../../App/View/css/bootstrap.min.css" rel="stylesheet">
<!-- Font Awesome -->
<link href="../../App/View/css/fontawesome-all.min.css" rel="stylesheet">
<script defer src="../../App/View/js/fontawesome-all.min.js"></script>
<!-- NProgress -->
<link href="../../App/View/css/nprogress.css" rel="stylesheet">
<!-- iCheck -->
<link href="../../App/View/icheck/skins/square/blue.css" rel="stylesheet">
<!-- Custom Theme Style -->
<link href="../../App/View/css/custom.min.css" rel="stylesheet">
<link href="../../App/View/css/base-style.css" rel="stylesheet">
<link href="../../App/View/css/custom-style-override.css" rel="stylesheet">
</head>

<body class="nav-md">
<div class="container body">
  <div class="main_container">

    <div class="col-md-3 left_col">
      <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
          <a href="../admin" class="site_title"><img src="../../App/View/img/logo.svg" id="sidebar-logo" alt="Logo"><span id="sidebar-logo-text"><span>TI</span> <span>CCHLA</span></span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
          <div class="profile_pic">
            <img src="" alt="..." class="img-circle profile_img">
          </div>
          <div class="profile_info">
            <span>Bem-vindo,</span>
            <h2><?php echo $_SESSION['user_name'];?></h2>
          </div>
        </div>
        <!-- /menu profile quick info -->

        <br />

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
              <h3></h3>
              <ul class="nav side-menu">
                <li><a href="../admin"><i class="fas fa-home"></i> Início</a>
                </li>

                <li><a>
                  <span class="fa-layers fa-fw">
                    <i class="fas fa-user"></i>
                    <i class="fas fa-wrench" data-fa-transform="shrink-2 down-4.2 right-7" style="color:#2DA7F9;"></i>
                  </span> Equipe</a>
                </li>

                <li><a>
                  <span class="fa-layers fa-fw">
                    <i class="fas fa-users"></i>
                    <i class="fas fa-bullhorn" data-fa-transform="shrink-2 right-8 down-8" style="color:#2DA7F9;"></i>
                  </span> Clientes</a>
                </li>

                <li><a>
                    <span class="fa-layers fa-fw">
                      <i class="fas fa-list"></i>
                      <i class="fas fa-bullhorn" data-fa-transform="shrink-2 right-8 down-6" style="color:#2DA7F9;"></i>
                    </span> Chamados</a>
                </li>

                <li><a href="./cadastro_usuarios">
                  <span class="fa-layers fa-fw">
                    <i class="fas fa-user"></i>
                    <i class="fas fa-plus" data-fa-transform="shrink-7 right-12" style="color:#2DA7F9;"></i>
                  </span> Cadastro de Usuario</a>
                </li>

              </ul>
              </div>

        </div>
        <!-- /sidebar menu -->

        <!-- /menu footer buttons -->
        <!--<div class="sidebar-footer hidden-small">
          <a data-toggle="tooltip" data-placement="top" title="Settings">
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
          </a>
          <a data-toggle="tooltip" data-placement="top" title="FullScreen">
            <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
          </a>
          <a data-toggle="tooltip" data-placement="top" title="Lock">
            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
          </a>
          <a data-toggle="tooltip" data-placement="top" title="Logout" href="../logout">
            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
          </a>
        </div> -->
        <!-- /menu footer buttons -->
      </div>
    </div>

    <!-- top navigation -->
    <div class="top_nav">
      <div class="nav_menu">
        <nav>
          <div class="nav toggle">
            <a id="menu_toggle"><i class="fas fa-bars"></i></a>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <i class="fas fa-user"></i> <?php echo $_SESSION['user_name'];?>
                <span class="fas fa-angle-down"></span>
              </a>
              <ul class="dropdown-menu dropdown-usermenu pull-right">
                <li>
                  <a href="../logout" data-original-title="Sair">
                    <i class="fas fa-sign-out-alt pull-right"></i> Sair
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </nav>
      </div>
    </div>
    <!-- /top navigation -->

    <!-- page content -->

    <div class="right_col" role="main">
      <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-10 col-xl-9">
              <div class="x_panel">
                <div class="x_title">
                  <h2>SOLICITAÇÕES<small>de acesso</small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fas fa-angle-up" data-fa-transform="grow-8"></i></a>
                    </li>
                    <!--<li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fas fa-cog"></i></a>
                    </li>-->
                    <!-- <li><a class="close-link"><i class="fas fa-times"></i></a> -->
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <form name="cadastro_usuario" method="post" action="cadastrar_usuarios">
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>Cliente</th>
                        <th>Setor</th>
                        <th>Selecionar</th>
                        <th> | </th>
                        <th>Permissões:</th>
                        <th>Cliente</th>
                        <th>Técnico</th>
                        <th>Gerente</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php foreach ($this->view->requisicoes as $requisicao):?>
                        <tr>
                            <td><?php echo $requisicao['nome'];?></td>
                            <td><?php echo $requisicao['setor'];?></td>
                            <td> <input type="checkbox" value=<?php echo $requisicao['id'];?> name="selections[]" id="r_id_<?php echo $requisicao['id']; ?>" /></td>
                            <td></td>
                            <td></td>
                            <td><input type="checkbox" value=<?php echo $requisicao['id'];?> name="client_role[]" id="r_client_role_<?php echo $requisicao['id']; ?>" /></td>
                            <td><input type="checkbox" value=<?php echo $requisicao['id'];?> name="technician_role[]" id="r_technician_role_<?php echo $requisicao['id']; ?>" /></td>
                            <td><input type="checkbox" value=<?php echo $requisicao['id'];?> name="manager_role[]" id="r_manager_role_<?php echo $requisicao['id']; ?>" /></td>
                        </tr>
                      <?php endforeach;?>
                    </tbody>
                  </table>
                  <input type="hidden" name="f_accept" value="f_accept"/>
                  <input class="btn btn-default" type="submit" value="Cadastrar Usúario(s)" name="accept" disabled/>
                </form>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
          </div>
    </div>
    <!-- /page content -->

    <!-- footer content -->
    <!--<footer>

    </footer>-->
    <!-- /footer content -->
    <!-- SCRIPTS DASHBOARD THEME-->

  </div>
</div>
<!-- jQuery -->
<script src="../../App/View/js/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="../../App/View/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="../../App/View/js/fastclick.js"></script>
<!-- NProgress -->
<script src="../../App/View/js/nprogress.js"></script>
<!-- iCheck -->
<script src="../../App/View/js/icheck.min.js"></script>
<script>
$(document).ready(function(){
$('input').iCheck({
  checkboxClass: 'icheckbox_square-blue',
  radioClass: 'iradio_square'
});
});
</script>
<!-- Custom Theme Scripts -->
<script src="../../App/View/js/custom.min.js"></script>

<!-- Check if there is any solicitation selected -->
<script>
var btn_cadastrar = $('form[name=cadastro_usuario] input[type=submit]');

function check_validity () {
  var valid_form = true;
  var has_valid_option = false;
  $('input[name="selections[]"]').each(function() {
    var id = this.value;
    var selection_checked = $('input[id=r_id_'+id+']')[0].checked;
    var client_role_checked = $('input[id=r_client_role_'+id+']')[0].checked;
    var technician_role_checked = $('input[id=r_technician_role_'+id+']')[0].checked;
    var manager_role_checked = $('input[id=r_manager_role_'+id+']')[0].checked;
    if (!selection_checked && (!client_role_checked && !technician_role_checked && !manager_role_checked)) {
      $(this).parents('tr').css("background-color", "initial");
      $(this).parents('tr').css("color", "inherit");
    }
    if (selection_checked && (client_role_checked || technician_role_checked || manager_role_checked)) {
      has_valid_option = true;
      $(this).parents('tr').css("background-color", "initial");
      $(this).parents('tr').css("color", "inherit");
    }
    if ((selection_checked && (!client_role_checked && !technician_role_checked && !manager_role_checked)) || (!selection_checked && (client_role_checked || technician_role_checked || manager_role_checked))) {
      valid_form = false;
      $(this).parents('tr').css("background-color", "#ff000033");
      $(this).parents('tr').css("color", "#a70000");
    }
  });
  if (has_valid_option && valid_form) {
    btn_cadastrar.removeClass('btn-default');
    btn_cadastrar.addClass('btn-primary');
    btn_cadastrar.prop('disabled', false);
  } else {
    btn_cadastrar.addClass('btn-default');
    btn_cadastrar.removeClass('btn-primary');
    btn_cadastrar.prop('disabled', true);
  }
}

$('input').on('ifChecked', function(event) {
  check_validity();
});
$('input').on('ifUnchecked', function(event) {
  check_validity();
});
</script>
</body>
