<!-- Layout Dashboard-->
<!-- Bootstrap -->
<link href="../../App/View/css/bootstrap.min.css" rel="stylesheet">
<!-- Font Awesome -->
<link href="../../App/View/css/fontawesome-all.min.css" rel="stylesheet">
<script defer src="../../App/View/js/fontawesome-all.min.js"></script>
<!-- NProgress -->
<link href="../../App/View/css/nprogress.css" rel="stylesheet">
<!-- iCheck -->
<link href="../../App/View/icheck/skins/square/blue.css" rel="stylesheet">
<!-- Custom Theme Style -->
<link href="../../App/View/css/custom.min.css" rel="stylesheet">
<link href="../../App/View/css/base-style.css" rel="stylesheet">
<link href="../../App/View/css/custom-style-override.css" rel="stylesheet">
<link href="../../App/View/css/account-request-page.css" rel="stylesheet">
</head>

<body class="nav-md">
<div class="container body">
  <div class="main_container">

    <div class="col-md-3 left_col">
      <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
          <a href="../admin" class="site_title"><img src="../../App/View/img/logo.svg" id="sidebar-logo" alt="Logo"><span id="sidebar-logo-text"><span>TI</span> <span>CCHLA</span></span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
          <div class="profile_pic">
            <img src="" alt="..." class="img-circle profile_img">
          </div>
          <div class="profile_info">
            <span>Bem-vindo,</span>
            <h2><?php echo $_SESSION['user_name'];?></h2>
          </div>
        </div>
        <!-- /menu profile quick info -->

        <br />

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
              <h3></h3>
              <ul class="nav side-menu">
                <li><a href="../admin"><i class="fas fa-home"></i> Início</a>
                </li>

                <li><a>
                  <span class="fa-layers fa-fw">
                    <i class="fas fa-user"></i>
                    <i class="fas fa-wrench" data-fa-transform="shrink-2 down-4.2 right-7" style="color:#2DA7F9;"></i>
                  </span> Equipe</a>
                </li>

                <li><a>
                  <span class="fa-layers fa-fw">
                    <i class="fas fa-users"></i>
                    <i class="fas fa-bullhorn" data-fa-transform="shrink-2 right-8 down-8" style="color:#2DA7F9;"></i>
                  </span> Clientes</a>
                </li>

                <li><a>
                    <span class="fa-layers fa-fw">
                      <i class="fas fa-list"></i>
                      <i class="fas fa-bullhorn" data-fa-transform="shrink-2 right-8 down-6" style="color:#2DA7F9;"></i>
                    </span> Chamados</a>
                </li>

                <li><a href="./cadastro_usuarios">
                  <span class="fa-layers fa-fw">
                    <i class="fas fa-user"></i>
                    <i class="fas fa-plus" data-fa-transform="shrink-7 right-12" style="color:#2DA7F9;"></i>
                  </span> Cadastro de Usuario</a>
                </li>

              </ul>
              </div>

        </div>
        <!-- /sidebar menu -->

        <!-- /menu footer buttons -->
        <!--<div class="sidebar-footer hidden-small">
          <a data-toggle="tooltip" data-placement="top" title="Settings">
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
          </a>
          <a data-toggle="tooltip" data-placement="top" title="FullScreen">
            <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
          </a>
          <a data-toggle="tooltip" data-placement="top" title="Lock">
            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
          </a>
          <a data-toggle="tooltip" data-placement="top" title="Logout" href="../logout">
            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
          </a>
        </div> -->
        <!-- /menu footer buttons -->
      </div>
    </div>

    <!-- top navigation -->
    <div class="top_nav">
      <div class="nav_menu">
        <nav>
          <div class="nav toggle">
            <a id="menu_toggle"><i class="fas fa-bars"></i></a>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <i class="fas fa-user"></i> <?php echo $_SESSION['user_name'];?>
                <span class="fas fa-angle-down"></span>
              </a>
              <ul class="dropdown-menu dropdown-usermenu pull-right">
                <li>
                  <a href="../logout" data-original-title="Sair">
                    <i class="fas fa-sign-out-alt pull-right"></i> Sair
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </nav>
      </div>
    </div>
    <!-- /top navigation -->

    <!-- page content -->

    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Solicitações de acesso</h3>
                </div>
                <div class="title_right">
                    <div class="pull-right">
                        <button id="btn-new-user" type="button" class="btn btn-primary"><i class="fas fa-plus"></i> Criar novo usuário</button>
                    </div>
                </div>
            </div>
            <div class="clearfix">
            </div>
            <div id="selection-options-wrapper" class="row col-xs-12">
              <button id="accept-selection" class="btn btn-default" disabled>Aceitar selecionados</button>
              <button id="archive-selection" class="btn btn-default" disabled>Arquivar selecionados</button>
            </div>
            <div id="request-list-wrapper" class="row">
              <?php foreach ($this->view->requisicoes as $requisicao):?>
              <div class="col-xs-12 col-lg-6">
                <div class="x_panel">
                    <div class="x_title" data-id-solicitacao="<?php echo $requisicao['id'];?>" data-nome="<?php echo $requisicao['nome'];?>" data-usuario="<?php echo $requisicao['login'];?>" data-email="<?php echo $requisicao['email'];?>" data-setor="<?php echo $requisicao['setor'];?>" data-matricula="<?php echo $requisicao['matricula'];?>">
                        <input type="checkbox" value="<?php echo $requisicao['id'];?>" name="selections[]" id="r_client_role_<?php echo $requisicao['id'];?>" />
                        <label for="r_client_role_<?php echo $requisicao['id'];?>"><h2><?php echo $requisicao['nome'];?></h2></label>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><button type="button" class="btn btn-primary btn-edit-request" title="Editar dados" value="<?php echo $requisicao['id'];?>"><i class="fas fa-pencil-alt"></i></button></li>
                            <li><button type="button" class="btn btn-primary btn-refuse-request" title="Recusar solicitação" value="<?php echo $requisicao['id'];?>"><i class="fas fa-times"></i></button></li>
                            <li><button type="button" class="btn btn-primary btn-accept-request" title="Cadastrar usuário" value="<?php echo $requisicao['id'];?>"><i class="fas fa-check"></i> Cadastrar</button></li>
                        </ul>
                        <div class="clearfix">
                        </div>
                    </div>
                    <div class="x_content">
                        <div class="request-info-summary-wrapper">
                            <div class="info-column">
                                <h4>Usuário</h4>
                                <h4>E-mail</h4>
                                <h4>Unidade de lotação</h4>
                                <h4>Matrícula</h4>
                            </div>
                            <div class="value-column">
                                <h4><?php echo $requisicao['login'];?></h4>
                                <h4><?php echo $requisicao['email'];?></h4>
                                <h4><?php echo $requisicao['setor'];?></h4>
                                <h4><?php echo $requisicao['matricula'];?></h4>
                            </div>
                        </div>
                    </div>
                </div>
              </div>
              <?php endforeach;?>
            </div>
        </div>
    </div>
    <!-- /page content -->

    <!-- footer content -->
    <!--<footer>

    </footer>-->
    <!-- /footer content -->
    <!-- SCRIPTS DASHBOARD THEME-->

  </div>

  <!-- Edit request/Register new user modal -->
  <div id="edit-request-modal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title"></h4>
        </div>
        <div class="modal-body">
          <form id="edit-request-form" class="form-horizontal">
            <input type="hidden" class="form-control" id="id_solicitacao_field">
            <div class="form-group">
              <label for="nome_field" class="col-sm-4 control-label">Nome</label>
              <div class="col-sm-8">
                <input type="text" class="form-control" id="nome_field">
              </div>
            </div>
            <div class="form-group">
              <label for="usuario_field" class="col-sm-4 control-label">Usuário</label>
              <div class="col-sm-8">
                <input type="text" class="form-control" id="usuario_field">
              </div>
            </div>
            <div class="form-group">
              <label for="email_field" class="col-sm-4 control-label">E-mail</label>
              <div class="col-sm-8">
                <input type="text" class="form-control" id="email_field">
              </div>
            </div>
            <div class="form-group">
              <label for="lotacao_field" class="col-sm-4 control-label">Unidade de lotação</label>
              <div class="col-sm-8">
                <input type="text" class="form-control" id="lotacao_field">
              </div>
            </div>
            <div class="form-group">
              <label for="matricula_field" class="col-sm-4 control-label">Matrícula</label>
              <div class="col-sm-8">
                <input type="text" class="form-control" id="matricula_field">
              </div>
            </div>
            <div class="form-group">
              <label for="role_field" class="col-sm-4 control-label">Atividade</label>
              <div class="col-sm-8" style="padding-top: 8px;">
                <div class="form-group">
                  <input type="checkbox" class="form-control" id="client_role_field">
                  <label for="client_role_field" style="font-weight: 600; margin-left: 10px; cursor: pointer;">Cliente</label>
                </div>
                <div class="form-group">
                  <input type="checkbox" class="form-control" id="technician_role_field">
                  <label for="technician_role_field" style="font-weight: 600; margin-left: 10px; cursor: pointer;">Técnico</label>
                </div>
                <div class="form-group">
                  <input type="checkbox" class="form-control" id="admin_role_field">
                  <label for="admin_role_field" style="font-weight: 600; margin-left: 10px; cursor: pointer;">Gerente</label>
                </div>
              </div>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button id="edit-modal-btn-cancel" type="button" class="btn btn-primary">Cancelar</button>
          <button id="edit-modal-btn-confirm" type="button" class="btn btn-primary">Cadastrar</button>
        </div>
      </div>
    </div>
  </div>

  <!-- Archive request modal -->
  <div id="archive-request-modal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">Arquivar solicitação</h4>
        </div>
        <div class="modal-body">
          <form id="archive-request-form" class="form-horizontal">
            <div class="form-group">
              <label for="request-refusal-reason-field" class="col-sm-4 control-label">Motivo</label>
              <div class="col-sm-8">
                <input type="text" class="form-control" id="request-refusal-reason-field">
              </div>
            </div>
            <div class="form-group">
              <label for="role_field" class="col-sm-4 control-label">Enviar e-mail</label>
              <div class="col-sm-8" style="padding-top: 8px;">
                <div class="form-group">
                  <input type="checkbox" class="form-control" id="notify-requester" checked>
                  <label for="notify-requester" style="font-weight: 600; margin-left: 10px; cursor: pointer;">notificar solicitante por e-mail</label>
                </div>
              </div>
            </div>
            <div id="email-composer-form-group" class="form-group">
              <label for="email-composer-wrapper" class="col-sm-4 control-label">Mensagem do e-mail</label>
              <div id="email-composer-wrapper" class="col-sm-8">
                <p>
                  Prezad@, <span id="archive-modal-requester-name"></span><br>
                  Infelizmente, sua conta não pôde ser efetivada pelo seguinte motivo:
                </p>
                <textarea id="email-request-refusal-reason" rows="3"></textarea>
                <p>
                  Se você acredita que houve um engano, sinta-se à vontade para responder esse e-mail!<br>
                  Atenciosamente,<br>
                  GTI CCHLA.
                </p>
              </div>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button id="archive-modal-btn-cancel" type="button" class="btn btn-primary">Cancelar</button>
          <button id="archive-modal-btn-confirm" type="button" class="btn btn-primary">Arquivar</button>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- jQuery -->
<script src="../../App/View/js/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="../../App/View/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="../../App/View/js/fastclick.js"></script>
<!-- NProgress -->
<script src="../../App/View/js/nprogress.js"></script>
<!-- iCheck -->
<script src="../../App/View/js/icheck.min.js"></script>
<script>
$(document).ready(function(){
$('input').iCheck({
  checkboxClass: 'icheckbox_square-blue',
  radioClass: 'iradio_square'
});
});
</script>
<!-- Custom Theme Scripts -->
<script src="../../App/View/js/custom.min.js"></script>

<!-- Check if there is any solicitation selected -->
<script>
var btn_cadastrar = $('div#request-list-wrapper input[type=submit]');

function toggleOptionsButtons () {
  if ($('div#request-list-wrapper input[type=checkbox]:checked').length > 0) {
    $('button#accept-selection').removeClass("btn-default");
    $('button#accept-selection').addClass("btn-primary");
    $('button#accept-selection').prop("disabled", false);
    $('button#archive-selection').removeClass("btn-default");
    $('button#archive-selection').addClass("btn-primary");
    $('button#archive-selection').prop("disabled", false);
  } else {
    $('button#accept-selection').addClass("btn-default");
    $('button#accept-selection').removeClass("btn-primary");
    $('button#accept-selection').prop("disabled", true);
    $('button#archive-selection').addClass("btn-default");
    $('button#archive-selection').removeClass("btn-primary");
    $('button#archive-selection').prop("disabled", true);
  }
}

$('div#request-list-wrapper input').on('ifChecked', function(event) {
  toggleOptionsButtons();
});
$('div#request-list-wrapper input').on('ifUnchecked', function(event) {
  toggleOptionsButtons();
});
</script>

<!-- Edit request/Register new user modal -->
<script>
  // Configuração do modal de novo usuário
  $('#btn-new-user').on('click', function() {
    $('#edit-request-modal h4.modal-title').text("Criar novo usuário");
    $('#edit-request-modal').modal('show');
    $('#edit-request-modal').on('shown.bs.modal', function(){
      $('#nome_field').get(0).focus();
      $('#edit-request-modal').off('shown.bs.modal');
    });
  });

  // Configuração do modal de editar usuário
  $('button.btn-edit-request').on('click', function(e) {
    $('#edit-request-modal h4.modal-title').text("Corrigir e cadastrar");

    // Preencher modal
    var dataset_DOM = $(e.currentTarget).parents('.x_title')[0].dataset;
    var dataset = JSON.parse(JSON.stringify(dataset_DOM));
    $('#id_solicitacao_field').val(dataset.idSolicitacao);
    $('#nome_field').val(dataset.nome);
    $('#usuario_field').val(dataset.usuario);
    $('#email_field').val(dataset.email);
    $('#lotacao_field').val(dataset.setor);
    $('#matricula_field').val(dataset.matricula);
    $('#client_role_field').iCheck("check");

    $('#edit-request-modal').modal('show');
  });

  // Ao fechar o modal
  $('#edit-request-modal').on('hidden.bs.modal', function() {
    $('#id_solicitacao_field').val("");
    $('#nome_field').val("");
    $('#usuario_field').val("");
    $('#email_field').val("");
    $('#lotacao_field').val("");
    $('#matricula_field').val("");
    $('#client_role_field').iCheck("uncheck");
    $('#technician_role_field').iCheck("uncheck");
    $('#admin_role_field').iCheck("uncheck");
  });


  // Botões do modal

  // Cancelar
  $('#edit-modal-btn-cancel').on('click', function() {
    $('#edit-request-modal').modal('hide');
  });

  // Confirmar
  $('#edit-modal-btn-confirm').on('click', function() {
    // Check if all necessary info was given
    var formIsValid = true;
    $('#edit-request-form input[type=text]').each(function() {
      if ($(this).val().match(/^\s*$/)) {
        formIsValid = false;
        return false;
      }
    });
    if ($('#edit-request-form input[type=checkbox]:checked').length == 0) {
      formIsValid = false;
    }

    // If info is complete, send to the server
    if (formIsValid) {
      var user_data = {
        nome: $('#nome_field').val(),
        email: $('#email_field').val(),
        usuario: $('#usuario_field').val(),
        setor: $('#lotacao_field').val(),
        matricula: $('#matricula_field').val(),
        isClient: ($('#client_role_field')[0].checked) ? 1 : 0,
        isTechnician: ($('#technician_role_field')[0].checked) ? 1 : 0,
        isAdmin: ($('#admin_role_field')[0].checked) ? 1 : 0
      };
      if ($('#id_solicitacao_field').val() != "") {
        user_data.idSolicitacao = $('#id_solicitacao_field').val();
      }

      $.post("/gticchla/public/admin/cadastrar_usuarios", {
        "new_user": user_data
      })
      .done(function() {
        alert("Usuário adicionado");
      })
      .fail(function() {
        //
      });
    } else {
      alert("Preencha todos os campos");
    }
  });
</script>

<!-- Archive request modal -->
<script>
  var requests = [];

  // Ao abrir o modal
  $('.btn-refuse-request').on('click', function(e) {
    // Get request data
    var request_dataset = $(e.currentTarget).parents('.x_title')[0].dataset;
    var request_data = JSON.parse(JSON.stringify(request_dataset));
    requests = [];
    requests.push(request_data);

    $('#archive-modal-requester-name').text(request_data.requester_name);
    $('#archive-request-modal').modal('show');
    $('#archive-request-modal').on('shown.bs.modal', function(){
      $('#request-refusal-reason-field').get(0).focus();
      $('#archive-request-modal').off('shown.bs.modal');
    });
  });

  // Ao selecionar/deselecionar opção de enviar e-mail notificando
  $('#notify-requester').on('ifChecked', function(event) {
    $("#email-composer-form-group").css("display", "block");
  });
  $('#notify-requester').on('ifUnchecked', function(event) {
    $("#email-composer-form-group").css("display", "none");
  });

  // Ao fechar o modal
  $('#archive-request-modal').on('hidden.bs.modal', function() {
    $('#id_solicitacao_field').val("");
    $('#request-refusal-reason-field').val("");
    $('#email-request-refusal-reason').val("");
    $('#notify-requester').iCheck('check');
  });

  // Botões do modal

  // Cancelar
  $('#archive-modal-btn-cancel').on('click', function() {
    $('#archive-request-modal').modal('hide');
  });

  // Confirmar
  $('#archive-modal-btn-confirm').on('click', function() {
    // Check if all necessary info was given
    var formIsValid = true;
    var refusal_reason = $('#request-refusal-reason-field').val();
    var refusal_email_message = $('#email-request-refusal-reason').val();
    var send_email = $('#notify-requester').get(0).checked;

    if (refusal_reason.match(/^\s*$/)) {
      formIsValid = false;
      alert("Insira o motivo da recusa");
      return false;
    }
    if (send_email) {
      if (refusal_email_message.match(/^\s*$/)) {
        formIsValid = false;
        alert("Escreva uma explicação no campo do e-mail");
        return false;
      }
    }

    // If info is complete, send to the server
    if (formIsValid) {
      var refusal_info = {
        "reason": refusal_reason,
        "send_email": send_email,
        "email_message": refusal_email_message,
        "request_list": requests
      }
      $.post("/gticchla/public/admin/archive_account_request", refusal_info)
      .done(function(data){
        alert("Feito!");
        window.location.reload(true);
      })
      .fail(function(data){
        // Failure
        if (data && data.responseJSON) {
          var response = data.responseJSON;
          if (response.event == "error") {
            if (response.type == "insuficient_data") {
              alert("Não foi possível realizar a ação por falta de dados");
            } else if(response.type == "insuficient_email_data") {
              alert("Não foi possível realizar a ação por insuficiência de dados para envio de email");
            } else {
              alert("Houve uma falha inesperada.\nNão foi possível completar a ação.");
            }
          } else {
            alert("Houve uma falha inesperada.\nNão foi possível completar a ação.");
          }
        }
      });
    }
  });
</script>

<!-- Requests actions -->
<script>
// Aceitar solicitações de cadastro selecionadas
$('button#accept-selection').on('click', function() {
  getSelectedRequests();
  $.post("/gticchla/public/admin/cadastrar_usuarios", {
    "requests": requests
  })
  .done(function() {
      requests = [];
      document.location.reload(true);
  })
  .fail(function() {
      requests = [];
  });
});

// Arquivar solicitações de cadastro selecionadas
$('button#archive-selection').on('click', function() {
  getSelectedRequests();

  $('#archive-modal-requester-name').text("<Nome do Cliente>");
  $('#archive-request-modal').modal('show');
  $('#archive-request-modal').on('shown.bs.modal', function(){
    $('#request-refusal-reason-field').get(0).focus();
    $('#archive-request-modal').off('shown.bs.modal');
  });
});

// Preeche lista de solicitações selecionadas
function getSelectedRequests() {
  requests = [];
  $('#request-list-wrapper input[type=checkbox]:checked').each(function() {
    var dataset = $(this).parents('.x_title')[0].dataset;
    var dataset_obj = JSON.parse(JSON.stringify(dataset));
    requests.push(dataset_obj);
  });
}

// Aceitar diretamente sem alterações
$('div#request-list-wrapper button.btn-accept-request').on('click', function() {
    var dataset = $(this).parents('.x_title')[0].dataset;
    var dataset_obj = JSON.parse(JSON.stringify(dataset));

    $.post("/gticchla/public/admin/cadastrar_usuarios", {
        "new_user": dataset_obj
    })
    .done(function() {
        document.location.reload(true);
    })
    .fail(function() {

    });
});
</script>
</body>
