<!-- Layout Dashboard-->
<!-- Bootstrap -->
<link href="../App/View/css/bootstrap.min.css" rel="stylesheet">
<!-- Font Awesome -->
<link href="../App/View/css/fontawesome-all.min.css" rel="stylesheet">
<script defer src="../App/View/js/fontawesome-all.min.js"></script>
<!-- NProgress -->
<link href="../App/View/css/nprogress.css" rel="stylesheet">
<!-- Custom Theme Style -->
<link href="../App/View/css/custom.min.css" rel="stylesheet">
<link href="../App/View/css/base-style.css" rel="stylesheet">
<link href="../App/View/css/custom-style-override.css" rel="stylesheet">
<link href="../App/View/css/custom-modal.css" rel="stylesheet">
</head>

<body class="nav-md">
  <div class="container body">
    <div class="main_container">

      <div class="col-md-3 left_col">
        <div class="left_col scroll-view">
          <div class="navbar nav_title" style="border: 0;">
            <a href="./admin" class="site_title"><img src="../App/View/img/logo.svg" id="sidebar-logo" alt="Logo"><span id="sidebar-logo-text"><span>TI</span> <span>CCHLA</span></span></a>
          </div>

          <div class="clearfix"></div>

          <!-- menu profile quick info -->
          <div class="profile clearfix">
            <div class="profile_pic">
              <img src="" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
              <span>Bem-vindo,</span>
              <h2><?php echo $_SESSION['user_name'];?></h2>
            </div>
          </div>
          <!-- /menu profile quick info -->

          <br />

          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
              <h3></h3>
              <ul class="nav side-menu">
                <li><a href="./admin"><i class="fas fa-home"></i> Início</a>
                </li>

                <li>
                  <a href="admin/solicitar_atendimento">
                    <span class="fa-layers fa-fw">
                      <i class="fas fa-user"></i>
                      <i class="fas fa-wrench" data-fa-transform="shrink-4 down-4.2 right-7" style="color:#2DA7F9;"></i>
                    </span> Solicitar atendimento
                  </a>
                </li>

                <li><a>
                  <span class="fa-layers fa-fw">
                    <i class="fas fa-user"></i>
                    <i class="fas fa-wrench" data-fa-transform="shrink-2 down-4.2 right-7" style="color:#2DA7F9;"></i>
                  </span> Equipe</a>
                </li>

                <li><a>
                  <span class="fa-layers fa-fw">
                    <i class="fas fa-users"></i>
                    <i class="fas fa-bullhorn" data-fa-transform="shrink-2 right-8 down-8" style="color:#2DA7F9;"></i>
                  </span> Clientes</a>
                </li>

                <li><a>
                    <span class="fa-layers fa-fw">
                      <i class="fas fa-list"></i>
                      <i class="fas fa-bullhorn" data-fa-transform="shrink-2 right-8 down-6" style="color:#2DA7F9;"></i>
                    </span> Chamados</a>
                </li>

                <li><a href="admin/cadastro_usuarios">
                  <span class="fa-layers fa-fw">
                    <i class="fas fa-user"></i>
                    <i class="fas fa-plus" data-fa-transform="shrink-7 right-12" style="color:#2DA7F9;"></i>
                  </span> Cadastro de Usuario</a>
                </li>

              </ul>
            </div>

          </div>
        </div>
      </div>

      <!-- top navigation -->
      <div class="top_nav">
        <div class="nav_menu">
          <nav>
            <div class="nav toggle">
              <a id="menu_toggle"><i class="fas fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
              <li>
                <a href="" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                  <i class="fas fa-user"></i> <?php echo $_SESSION['user_name'];?>
                  <span class="fas fa-angle-down"></span>
                </a>
                <ul class="dropdown-menu dropdown-usermenu pull-right">
                  <li>
                    <a href="./admin/configuracoes" data-original-title="Configurações da conta">
                      <i class="fas fa-wrench pull-right"></i> Configurações da conta
                    </a>
                  </li>
                  <li>
                    <a href="logout" data-original-title="Sair">
                      <i class="fas fa-sign-out-alt pull-right"></i> Sair
                    </a>
                  </li>
                </ul>
              </li>
            </ul>
          </nav>
        </div>
      </div>
      <!-- /top navigation -->

      <!-- page content -->

      <div class="right_col" role="main">
        <div class="row">
          <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>CHAMADOS <small>Em atendimento</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fas fa-angle-up" data-fa-transform="grow-8"></i></a>
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>
              <div class="x_content">
                <table id="processing-requests" class="table table-hover clickable-rows">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Prazo</th>
                      <th>Cliente</th>
                      <th>Local</th>
                      <th>Serviço</th>
                      <th>Técnico Responsável</th>
                    </tr>
                  </thead>
                  <tbody></tbody>
                </table>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>CHAMADOS<small>aguardando aprovação</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fas fa-angle-up" data-fa-transform="grow-8"></i></a>
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>
              <div class="x_content">
                <form name="client_call_request">
                  <table id="call-request-list" class="table table-hover clickable-rows">
                    <thead>
                      <tr>
                        <th>Cliente</th>
                        <th>Local</th>
                        <th>Serviço</th>
                        <th>Ação</th>
                      </tr>
                    </thead>
                    <tbody></tbody>
                  </table>
              </form>
              </div>
            </div>
          </div>
          <div class="clearfix"></div>
          <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>CHAMADOS <small>Abertos</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fas fa-angle-up" data-fa-transform="grow-8"></i></a>
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>
              <div class="x_content">
                <table id="not-processing-requests" class="table table-hover clickable-rows">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Prazo</th>
                      <th>Cliente</th>
                      <th>Local</th>
                      <th>Serviço</th>
                      <th>Técnico Abertura</th>
                    </tr>
                  </thead>
                  <tbody></tbody>
                </table>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>SOLICITAÇÕES<small>de acesso</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fas fa-angle-up" data-fa-transform="grow-8"></i></a>
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>
              <div class="x_content">
                <table id="unreviewed-account-requests" class="table table-hover">
                  <thead>
                    <tr>
                      <th>Nome</th>
                      <th>Setor</th>
                    </tr>
                  </thead>
                  <tbody></tbody>
                </table>
              </div>
            </div>
          </div>
          <div class="clearfix"></div>
        </div>
      </div>
      <!-- /page content -->

      <!-- footer content -->
      <!-- <footer>

      </footer> -->
      <!-- /footer content -->
      <!-- SCRIPTS DASHBOARD THEME-->

    </div>

    <!-- REQUEST MODAL -->
    <div class="modal fade request-modal" tabindex="-1" role="dialog"></div>
  </div>
  <!-- jQuery -->
  <script src="../App/View/js/jquery.min.js"></script>
  <!-- Bootstrap -->
  <script src="../App/View/js/bootstrap.min.js"></script>
  <!-- NProgress -->
  <script src="../App/View/js/nprogress.js"></script>
  <!-- Moment.js -->
  <script src="../App/View/js/moment.min.js"></script>
  <!-- forge-sha256 -->
  <script src="../App/View/js/forge-sha256.min.js"></script>

  <!-- Socket.IO -->
  <script src="../App/View/js/socket.io.js"></script>
  <script>
    let token = <?php echo $this->view->token ?>;

    // Connect to the WebSocket server
    let socket = io(`ws://${window.location.host}:5530`);

    // Try to resolve the challenge in order to stay connected to the WS server
    socket.on('connecting', ({challenge}) => {
      let solution = `${challenge}${token.last_login_date}`;
      let tokenData = {
        "username": token.username,
        "challengeSolution": forge_sha256(solution)
      };
      socket.emit('challenge solution', tokenData);
    });

    // When a client makes a ticket request
    socket.on('client requested ticket', ticketRequest => {
      // Insert the ticket request in the page
      window.activeTicketRequests.push(ticketRequest);
      insertInActiveTicketRequestsTable(ticketRequest)
    });

    // When a client cancels a ticket request
    socket.on('client cancelled ticket request', ticketRequest => {
      // Remove the ticket request from the local list
      window.activeTicketRequests = window.activeTicketRequests.filter(
        r => r.id_solicitacao !== ticketRequest.id_solicitacao
      );

      // Remove the ticket request from the table
      $('form[name=client_call_request]').find(`[data-request-id=${ticketRequest.id_solicitacao}]`).remove();
    });

    // When a client cancels a ticket
    socket.on('client cancelled ticket', ticket => {
      // Remove the ticket from the "in queue" list and table
      window.inQueueTickets = window.inQueueTickets.filter(
        r => r.id_chamado !== ticket.id_chamado
      );
      $('table[id=not-processing-requests]').find(`[data-request-id=${ticket.id_chamado}]`).remove();
    });

    // When the support refuses a ticket request
    socket.on('support refused ticket request', ticketRequest => {
      // Remove the ticket request from the ticket requests list and table
      window.activeTicketRequests = window.activeTicketRequests.filter(
        r => r.id_solicitacao !== ticketRequest.id_solicitacao
      );
      $('form[name=client_call_request]').find(`[data-request-id=${ticketRequest.id_solicitacao}]`).remove();
    });

    // When the support accepts a ticket request
    socket.on('support accepted ticket request', ticket => {
      // Remove the ticket request from the ticket requests list and table
      window.activeTicketRequests = window.activeTicketRequests.filter(
        r => r.id_solicitacao !== ticket.id_solicitacao
      );
      $('form[name=client_call_request]').find(`[data-request-id=${ticket.id_solicitacao}]`).remove();
      // Insert into the "in queue" list and table
      window.inQueueTickets.push(ticket);
      insertInInQueueTicketsTable(ticket);
    });

    // When technicians acquire a ticket
    socket.on('technician acquired ticket', ticket => {
      // Remove the ticket from the "in queue" list and table
      window.inQueueTickets = window.inQueueTickets.filter(
        r => r.id_chamado !== ticket.id_chamado
      );
      $('table[id=not-processing-requests]').find(`[data-request-id=${ticket.id_chamado}]`).remove();
      // Insert into the "in process tickets" list and table
      window.inProcessTickets.push(ticket);
      insertInInProcessTicketsTable(ticket);
    });

    // When technicians finalize a ticket
    socket.on('technician finalized ticket', ticket => {
      // Remove from "in process tickets" list and table
      window.inProcessTickets = window.inProcessTickets.filter(
        r => r.id_chamado !== ticket.id_chamado
      );
      $('table[id=processing-requests]').find(`[data-request-id=${ticket.id_chamado}]`).remove();
    });
  </script>
  <!-- Custom Theme Scripts -->
  <script src="../App/View/js/custom.min.js"></script>

  <!-- Request modal settings -->
  <script src="../App/View/js/request-modals.js"></script>
  <script>
    function activeTicketRequestsTableRowClick(e) {
      if (e.target.nodeName == "TR" || e.target.nodeName == "TD") {
        var requestId = getRowId(e);
        if (requestId) {
          var modalConfig = {
            title: "Detalhes do chamado",
            visible_fields: {
              id_solicitacao_field: true,
              cliente_field: true,
              local_field: true,
              status_field: true,
              servico_field: true,
              data_solicitacao_field: true,
              descricao_field: true
            }
          };
          let requestData = activeTicketRequests.find(r => r.id_solicitacao === requestId);
          defineSimpleModal(modalConfig, requestData);
        }
      }
    }
    function acceptTicketRequestBtnClick(e) {
      if (e.target.nodeName == "BUTTON") {
        var requestId = getRowId(e);
        if (requestId) {
          var modalConfig = {
            title: "Aceitar solicitação de chamado",
            visible_fields: {
              id_solicitacao_field: true,
              cliente_field: true,
              servico_field: true,
              descricao_field: true,
              data_solicitacao_field: true,
              prazo_field: false
            },
            footer_config: [
              {
                btnContent: "Aceitar chamado",
                class: "btn btn-primary",
                callback: acceptRequest.bind(null, requestId)
              }
            ]
          };
          let requestData = activeTicketRequests.find(r => r.id_solicitacao === requestId);
          defineSimpleModal(modalConfig, requestData);
        }
      }
    }
    function refuseTicketRequestBtnClick(e) {
      if (e.target.nodeName == "BUTTON") {
        var requestId = getRowId(e);
        if (requestId) {
          var modalConfig = {
            title: "Recusar solicitação de chamado",
            visible_fields: {
              id_solicitacao_field: true,
              cliente_field: true,
              local_field: true,
              servico_field: true,
              data_solicitacao_field: true,
              descricao_field: true,
              motivo_recusa_field: false
            },
            footer_config: [
              {
                btnContent: "Recusar solicitação",
                class: "btn btn-primary",
                callback: refuseRequest.bind(null, requestId)
              }
            ]
          };
          let requestData = activeTicketRequests.find(r => r.id_solicitacao === requestId);
          let filledFormFields = ["id_solicitacao_field", "cliente_field", "local_field", "servico_field", "data_solicitacao_field", "descricao_field"];
          defineModal(modalConfig);
          fillUpRequestModal(requestData, filledFormFields);
          showRequestModal();
        }
      }
    }
    function inQueueTicketsTableRowClick(e) {
      if (e.target.nodeName == "TR" || e.target.nodeName == "TD") {
        var requestId = getRowId(e);
        if (requestId) {
          modalConfig = {
            title: "Detalhes do chamado",
            visible_fields: {
              id_chamado_field: true,
              status_field: true,
              cliente_field: true,
              local_field: true,
              servico_field: true,
              data_abertura_field: true,
              tecnico_abertura_field: true,
              descricao_field: true,
              prazo_field: true
            }
          };
          let requestData = inQueueTickets.find(r => r.id_chamado === requestId);
          defineSimpleModal(modalConfig, requestData);
        }
      }
    }
    function inProcessTicketsTableRowClick(e) {
      if (e.target.nodeName == "TR" || e.target.nodeName == "TD") {
        var requestId = getRowId(e);
        if (requestId) {
          var modalConfig = {
            title: "Detalhes do chamado",
            visible_fields: {
              id_chamado_field: true,
              status_field: true,
              cliente_field: true,
              local_field: true,
              servico_field: true,
              data_abertura_field: true,
              data_assumido_field: true,
              tecnico_abertura_field: true,
              descricao_field: true,
              prazo_field: true,
              tecnico_responsavel_field: true
            }
          };
          let requestData = inProcessTickets.find(r => r.id_chamado === requestId);
          defineSimpleModal(modalConfig, requestData);
        }
      }
    }
    function ticketRequestAccepted(ticket) {
      // Send the ticket request to connected support users and to the requester client
      socket.emit('from support', 'support accepted ticket request', ticket);

      // Put the ticket in the local open tickets list
      //  and remove from the active requests list
      window.inQueueTickets.push(ticket);
      window.activeTicketRequests = window.activeTicketRequests.filter(
        r => r.id_solicitacao !== ticket.id_solicitacao
      );

      // Remove the ticket request from the table it were before
      $('form[name=client_call_request]').find(`[data-request-id=${ticket.id_solicitacao}]`).remove();

      // Insert the ticket in the "In Queue" table
      insertInInQueueTicketsTable(ticket);
    }
    function ticketRequestRefused(request) {
      // Send the ticket request to connected support users and to the requester client
      socket.emit('from support', 'support refused ticket request', request);

      // Search for the request in the local list and delete it
      window.activeTicketRequests = window.activeTicketRequests.filter(
        r => r.id_solicitacao !== request.id_solicitacao
      );

      // Remove the request from the table
      $('form[name=client_call_request]').find(`[data-request-id=${request.id_solicitacao}]`).remove();
    }
  </script>

  <!-- Tables handling -->
  <script>
    const calculateDeadlineMsg = (deadlineDatetime) => {
      let a = moment();
      let b = moment(deadlineDatetime, "YYYY-MM-DD HH:mm:ss");
      let interval = b.diff(a, 'months');
      let deadlineMsg = "";
      if (interval >= 2 || interval <= -2) {
        // Months of difference
        deadlineMsg = (interval > 0) ? `Daqui a ${interval} meses` : `${Math.abs(interval)} meses atrasado`;
      } else {
        interval = b.diff(a, 'weeks');
        if (interval >= 2 || interval <= -2) {
          // Weeks of difference
          deadlineMsg = (interval > 0) ? `Daqui a ${interval} semanas` : `${Math.abs(interval)} semanas atrasado`;
        } else {
          interval = b.diff(a, 'days');
          if (interval >= 2 || interval <= -2) {
            // Days of difference
            deadlineMsg = (interval > 0) ? `Daqui a ${interval} dias` : `${Math.abs(interval)} dias atrasado`;
          } else {
            interval = b.diff(a, 'hours');
            if (interval >= 24 || interval <= -24) {
              deadlineMsg = (interval > 0) ? `Daqui a 2 dias` : `2 dias atrasado`;
            } else if (a.format("YYYY-MM-DD") === b.format("YYYY-MM-DD")) {
              deadlineMsg = "Hoje";
            } else {
              deadlineMsg = (interval > 0) ? `Daqui a 1 dia` : `1 dia atrasado`;
            }
          }
        }
      }
      return deadlineMsg;
    };

    function insertInUnreviewedAccountRequestsTable(request) {
      let unreviewedAccountRequestsTable = $('#unreviewed-account-requests');

      // Row structure
      let newRow = $("<tr>").attr("data-request-id", request.id);
      let cols = "";
      cols += `<td>${request.nome}</td>`;
      cols += `<td>${request.setor}</td>`;
      newRow.append(cols);

      // Add the row to the table
      unreviewedAccountRequestsTable.append(newRow);
    }
    function insertInActiveTicketRequestsTable(request) {
      let activeTicketRequestsTable = $('#call-request-list');

      // Row structure
      let newRow = $("<tr>").attr("data-request-id", request.id_solicitacao);

      let cols = "";
      cols += `<td>${request.cliente}</td>`;
      cols += `<td>${request.local}</td>`;
      cols += `<td>${request.servico}</td>`;
      newRow.append(cols);

      let btnAcceptRequest = $(
        `<button class="btn btn-primary"
        type="button"
        value="${request.id_solicitacao}"
        name="request-acceptance">Aceitar</button>`
      );

      let btnRefuseRequest = $(
        `<button class="btn btn-primary"
        type="button"
        value="${request.id_solicitacao}"
        name="request-refusal">Recusar</button>`
      );

      newRow.append($("<td>")
      .append(btnAcceptRequest)
      .append(btnRefuseRequest));

      // Events
      $(newRow).on('click', activeTicketRequestsTableRowClick);
      $(btnAcceptRequest).on('click', acceptTicketRequestBtnClick);
      $(btnRefuseRequest).on('click', refuseTicketRequestBtnClick);

      activeTicketRequestsTable.append(newRow);
    }
    function insertInInQueueTicketsTable(ticket) {
      let inQueueTicketsTable = $('#not-processing-requests');

      // Row structure
      let newRow = $("<tr>").attr("data-request-id", ticket.id_chamado);
      let cols = "";
      cols += `<td>${ticket.id_chamado}</td>`;
      cols += `<td>${calculateDeadlineMsg(request.prazo)}</td>`;
      cols += `<td>${ticket.cliente}</td>`;
      cols += `<td>${ticket.local}</td>`;
      cols += `<td>${ticket.servico}</td>`;
      cols += `<td>${ticket.tecnico_abertura}</td>`;
      newRow.append(cols);

      // Events
      $(newRow).on('click', inQueueTicketsTableRowClick);

      // Add the row to the table
      inQueueTicketsTable.append(newRow);
    }
    function insertInInProcessTicketsTable(ticket) {
      let inProcessTickesTable = $('#processing-requests');

      // Row structure
      let newRow = $("<tr>").attr("data-request-id", ticket.id_chamado);
      let cols = "";
      cols += `<td>${ticket.id_chamado}</td>`;
      cols += `<td>${calculateDeadlineMsg(ticket.prazo)}</td>`;
      cols += `<td>${ticket.cliente}</td>`;
      cols += `<td>${ticket.local}</td>`;
      cols += `<td>${ticket.servico}</td>`;
      cols += `<td>${ticket.tecnico_responsavel}</td>`;
      newRow.append(cols);

      // Events
      $(newRow).on('click', inProcessTicketsTableRowClick);

      // Add the row to the table
      inProcessTickesTable.append(newRow);
    }
  </script>

  <!-- Ready -->
  <script>
    const populateUnreviewedAccountRequests = () => {
      for (request of window.unreviewedAccountRequests) {
        insertInUnreviewedAccountRequestsTable(request);
      }
    }
    const populateActiveTicketRequestsTable = () => {
      for (request of window.activeTicketRequests) {
        insertInActiveTicketRequestsTable(request);
      }
    }
    const populateInQueueTicketsTable = () => {
      for (ticket of window.inQueueTickets) {
        insertInInQueueTicketsTable(ticket);
      }
    }
    const populateInProcessTicketsTable = () => {
      for (ticket of window.inProcessTickets) {
        insertInInProcessTicketsTable(ticket);
      }
    }

    $(document).ready(function() {
      // Load the requests for the page
      window.unreviewedAccountRequests = <?php echo json_encode($this->view->unreviewedAccountRequests) ?>;
      window.activeTicketRequests = <?php echo json_encode($this->view->activeTicketRequests) ?>;
      window.inQueueTickets = <?php echo json_encode($this->view->inQueueTickets) ?>;
      window.inProcessTickets = <?php echo json_encode($this->view->inProcessTickets) ?>;

      // Populate the tables
      populateUnreviewedAccountRequests();
      populateActiveTicketRequestsTable();
      populateInQueueTicketsTable();
      populateInProcessTicketsTable();
    });
  </script>
</body>
