  <!-- Layout Dashboard-->
  <!-- Bootstrap -->
  <link href="../App/View/css/bootstrap.min.css" rel="stylesheet">
  <!-- Font Awesome -->
  <link href="../App/View/css/fontawesome-all.min.css" rel="stylesheet">
  <script defer src="../App/View/js/fontawesome-all.min.js"></script>
  <!-- NProgress -->
  <link href="../App/View/css/nprogress.css" rel="stylesheet">
  <!-- iCheck -->
  <link href="../App/View/icheck/skins/square/blue.css" rel="stylesheet">
  <!-- Custom Theme Style -->
  <link href="../App/View/css/custom.min.css" rel="stylesheet">
  <link href="../App/View/css/base-style.css" rel="stylesheet">
  <link href="../App/View/css/custom-style-override.css" rel="stylesheet">
  <link href="../App/View/css/custom-modal.css" rel="stylesheet">
</head>

<body class="nav-md">
  <div class="container body">
    <div class="main_container">

      <div class="col-md-3 left_col">
        <div class="left_col scroll-view">
          <div class="navbar nav_title" style="border: 0;">
            <a href="./admin" class="site_title"><img src="../App/View/img/logo.svg" id="sidebar-logo" alt="Logo"><span id="sidebar-logo-text"><span>TI</span> <span>CCHLA</span></span></a>
          </div>

          <div class="clearfix"></div>

          <!-- menu profile quick info -->
          <div class="profile clearfix">
            <div class="profile_pic">
              <img src="" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
              <span>Bem-vindo,</span>
              <h2><?php echo $_SESSION['user_name'];?></h2>
            </div>
          </div>
          <!-- /menu profile quick info -->

          <br />

          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
              <h3></h3>
              <ul class="nav side-menu">
                <li><a href="./admin"><i class="fas fa-home"></i> Início</a>
                </li>

                <li><a>
                  <span class="fa-layers fa-fw">
                    <i class="fas fa-user"></i>
                    <i class="fas fa-wrench" data-fa-transform="shrink-2 down-4.2 right-7" style="color:#2DA7F9;"></i>
                  </span> Equipe</a>
                </li>

                <li><a>
                  <span class="fa-layers fa-fw">
                    <i class="fas fa-users"></i>
                    <i class="fas fa-bullhorn" data-fa-transform="shrink-2 right-8 down-8" style="color:#2DA7F9;"></i>
                  </span> Clientes</a>
                </li>

                <li><a>
                    <span class="fa-layers fa-fw">
                      <i class="fas fa-list"></i>
                      <i class="fas fa-bullhorn" data-fa-transform="shrink-2 right-8 down-6" style="color:#2DA7F9;"></i>
                    </span> Chamados</a>
                </li>

                <li><a href="admin/cadastro_usuarios">
                  <span class="fa-layers fa-fw">
                    <i class="fas fa-user"></i>
                    <i class="fas fa-plus" data-fa-transform="shrink-7 right-12" style="color:#2DA7F9;"></i>
                  </span> Cadastro de Usuario</a>
                </li>

              </ul>
            </div>

          </div>
          <!-- /sidebar menu -->

          <!-- /menu footer buttons -->
          <!--<div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
              <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
              <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
              <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout" href="logout">
              <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
          </div>-->
          <!-- /menu footer buttons -->
        </div>
      </div>

      <!-- top navigation -->
      <div class="top_nav">
        <div class="nav_menu">
          <nav>
            <div class="nav toggle">
              <a id="menu_toggle"><i class="fas fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
              <li>
                <a href="" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                  <i class="fas fa-user"></i> <?php echo $_SESSION['user_name'];?>
                  <span class="fas fa-angle-down"></span>
                </a>
                <ul class="dropdown-menu dropdown-usermenu pull-right">
                  <li>
                    <a href="logout" data-original-title="Sair">
                      <i class="fas fa-sign-out-alt pull-right"></i> Sair
                    </a>
                  </li>
                </ul>
              </li>
            </ul>
          </nav>
        </div>
      </div>
      <!-- /top navigation -->

      <!-- page content -->

      <div class="right_col" role="main">
        <div class="row tile_count">
          <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fas fa-user"></i> Total Chamados</span>
            <div class="count"><?php echo $this->view->count;?></div>
            <span class="count_bottom"><i class="green">4% </i>Resolvidos no prazo</span>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>CHAMADOS <small>Em atendimento</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fas fa-angle-up" data-fa-transform="grow-8"></i></a>
                  </li>
                  <!--<li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fas fa-cog"></i></a>
                  </li>-->
                  <!-- <li><a class="close-link"><i class="fas fa-times"></i></a> -->
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>
              <div class="x_content">
                <table class="table table-hover open-request-list">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Serviço</th>
                      <th>Setor</th>
                      <th>Técnico Responsável</th>
                    </tr>
                  </thead>
                  <tbody>
                    <?php foreach ($this->view->chamados_atendimentos as $atendimento):?>
                      <tr>
                        <td><?php echo $atendimento['id_solicitacao'];?></td>
                        <td><?php echo $this->view->service_names[$atendimento['id_servico']];?></td>
                        <td><?php echo $this->view->clients_names[$atendimento['id_cliente_solicitante']]['setor'];?></td>
                        <td><?php echo $this->view->clients_names[$atendimento['id_tecnico_responsavel']]['nome'];?></td>
                      </tr>
                    <?php endforeach;?>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>SOLICITAÇÕES<small>pendentes</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fas fa-angle-up" data-fa-transform="grow-8"></i></a>
                  </li>
                  <!--<li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fas fa-cog"></i></a>
                  </li>-->
                  <!-- <li><a class="close-link"><i class="fas fa-times"></i></a> -->
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>
              <div class="x_content">
                <form name="client_call_request" method="post" action="admin/open_call_request">
                  <table class="table table-hover call-request-list">
                    <thead>
                      <tr>
                        <th>ID</th>
                        <th>Cliente</th>
                        <th>Serviço</th>
                        <th>Setor</th>
                        <th>Descrição</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php foreach ($this->view->requisicoes_atendimento as $call_request): ?>
                        <tr>
                            <td><?php echo $call_request['id']; ?></td>
                            <td><?php echo $this->view->clients_names[$call_request['id_cliente']]['nome'];?></td>
                            <td><?php echo $this->view->service_names[$call_request['id_servico']];?></td>
                            <td><?php echo $this->view->clients_names[$call_request['id_cliente']]['setor'];?></td>
                            <td><?php echo $call_request['descricao'];?></td>
                            <td> <input type="checkbox" value=<?php echo $call_request['id'];?> name="selections_call_request[]"/></td>
                        </tr>
                      <?php endforeach; ?>
                    </tbody>
                  </table>
                <input type="hidden" name="admin_open_client_call_request" value="admin_open_client_call_request"/>
                <button type="submit" class="btn btn-default" disabled>Abrir Chamado</button>
              </form>
              </div>
            </div>
          </div>
          <div class="clearfix"></div>
          <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>CHAMADOS <small>Abertos</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fas fa-angle-up" data-fa-transform="grow-8"></i></a>
                  </li>
                  <!--<li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fas fa-cog"></i></a>
                  </li>-->
                  <!-- <li><a class="close-link"><i class="fas fa-times"></i></a> -->
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>
              <div class="x_content">
                <table class="table table-hover open-request-list">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Cliente</th>
                      <th>Serviço</th>
                      <th>Setor</th>
                      <th>Técnico Abertura</th>
                    </tr>
                  </thead>
                  <tbody>
                      <?php foreach ($this->view->chamados_abertos as $abertos):?>
                        <tr>
                          <td><?php echo $abertos['id'];?></td>
                          <td><?php echo $this->view->clients_names[$abertos['id_cliente_solicitante']]['nome'];?></td>
                          <td><?php echo $this->view->service_names[$abertos['id_servico']];?></td>
                          <td><?php echo $this->view->clients_names[$abertos['id_cliente_solicitante']]['setor'];?></td>
                          <td><?php echo $this->view->clients_names[$abertos['id_tecnico_abertura']]['nome'];?></td>
                        </tr>
                      <?php endforeach;?>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>SOLICITAÇÕES<small>de acesso</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fas fa-angle-up" data-fa-transform="grow-8"></i></a>
                  </li>
                  <!--<li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fas fa-cog"></i></a>
                  </li>-->
                  <!-- <li><a class="close-link"><i class="fas fa-times"></i></a> -->
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>
              <div class="x_content">
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th>Cliente</th>
                      <th>Setor</th>
                    </tr>
                  </thead>
                  <tbody>
                    <?php foreach ($this->view->requisicoes as $requisicao):?>
                      <tr>
                        <td><?php echo $requisicao['nome'];?></td>
                        <td><?php echo $requisicao['setor'];?></td>
                      </tr>
                    <?php endforeach;?>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <div class="clearfix"></div>
        </div>
      </div>
      <!-- /page content -->

      <!-- footer content -->
      <!-- <footer>

      </footer> -->
      <!-- /footer content -->
      <!-- SCRIPTS DASHBOARD THEME-->

    </div>

    <!-- REQUEST MODAL -->
    <div class="modal fade request-modal" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Detalhes do chamado</h4>
          </div>
          <div class="modal-body">
            <form class="form-horizontal call-request-modal-form">
              <div class="form-group">
                <label for="id_solicitacao_field" class="col-sm-4 control-label">Solicitação</label>
                <div class="col-sm-8">
                  <input type="text" class="form-control" id="id_solicitacao_field" readonly>
                </div>
              </div>
              <div class="form-group">
                <label for="status_field" class="col-sm-4 control-label">Status</label>
                <div class="col-sm-8">
                  <input type="text" class="form-control" id="status_field" readonly>
                </div>
              </div>
              <div class="form-group">
                <label for="servico_field" class="col-sm-4 control-label">Serviço</label>
                <div class="col-sm-8">
                  <input type="text" class="form-control" id="servico_field" readonly>
                </div>
              </div>
              <div class="form-group">
                <label for="data_solicitacao_field" class="col-sm-4 control-label">Data da solicitação</label>
                <div class="col-sm-8">
                  <input type="text" class="form-control" id="data_solicitacao_field" readonly>
                </div>
              </div>
              <div class="form-group">
                <label for="descricao_field" class="col-sm-4 control-label">Descrição</label>
                <div class="col-sm-8">
                  <input type="text" class="form-control" id="descricao_field" readonly>
                </div>
              </div>
            </form>
            <form class="form-horizontal open-request-modal-form">
              <div class="form-group">
                <label for="id_solicitacao_field" class="col-sm-4 control-label">Solicitação</label>
                <div class="col-sm-8">
                  <input type="text" class="form-control" id="id_solicitacao_field" readonly>
                </div>
              </div>
              <div class="form-group">
                <label for="status_field" class="col-sm-4 control-label">Status</label>
                <div class="col-sm-8">
                  <input type="text" class="form-control" id="status_field" readonly>
                </div>
              </div>
              <div class="form-group">
                <label for="servico_field" class="col-sm-4 control-label">Serviço</label>
                <div class="col-sm-8">
                  <input type="text" class="form-control" id="servico_field" readonly>
                </div>
              </div>
              <div class="form-group">
                <label for="data_abertura_field" class="col-sm-4 control-label">Data de abertura</label>
                <div class="col-sm-8">
                  <input type="text" class="form-control" id="data_abertura_field" readonly>
                </div>
              </div>
              <div class="form-group">
                <label for="data_finalizado_field" class="col-sm-4 control-label">Data finalizado</label>
                <div class="col-sm-8">
                  <input type="text" class="form-control" id="data_finalizado_field" readonly>
                </div>
              </div>
              <div class="form-group">
                <label for="prazo_field" class="col-sm-4 control-label">Prazo</label>
                <div class="col-sm-8">
                  <input type="text" class="form-control" id="prazo_field" readonly>
                </div>
              </div>
              <div class="form-group">
                <label for="tecnico_responsavel_field" class="col-sm-4 control-label">Técnico responsável</label>
                <div class="col-sm-8">
                  <input type="text" class="form-control" id="tecnico_responsavel_field" readonly>
                </div>
              </div>
              <div class="form-group">
                <label for="tecnico_abertura_field" class="col-sm-4 control-label">Técnico da abertura</label>
                <div class="col-sm-8">
                  <input type="text" class="form-control" id="tecnico_abertura_field" readonly>
                </div>
              </div>
              <div class="form-group">
                <label for="descricao_field" class="col-sm-4 control-label">Descrição</label>
                <div class="col-sm-8">
                  <input type="text" class="form-control" id="descricao_field" readonly>
                </div>
              </div>
              <div class="form-group">
                <label for="parecer_tecnico_field" class="col-sm-4 control-label">Parecer técnico</label>
                <div class="col-sm-8">
                  <textarea class="form-control" rows="3" id="parecer_tecnico_field" readonly></textarea>
                </div>
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
  </div>
  <!-- jQuery -->
  <script src="../App/View/js/jquery.min.js"></script>
  <!-- Bootstrap -->
  <script src="../App/View/js/bootstrap.min.js"></script>
  <!-- FastClick -->
  <script src="../App/View/js/fastclick.js"></script>
  <!-- NProgress -->
  <script src="../App/View/js/nprogress.js"></script>
  <!-- iCheck -->
  <script src="../App/View/js/icheck.min.js"></script>
  <script>
  $(document).ready(function(){
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square'
    });
  });
  </script>
  <!-- Custom Theme Scripts -->
  <script src="../App/View/js/custom.min.js"></script>
  <script src="../App/View/js/request-modals.js"></script>

  <!-- Check if there is any demand selected -->
  <script>
  var btn_abrir_chamado = $('form[name=client_call_request] > button[type=submit]');
  $('input').on('ifChecked', function(event) {
      if (btn_abrir_chamado.hasClass('btn-default')) {
          btn_abrir_chamado.toggleClass('btn-default btn-primary');
          btn_abrir_chamado.prop('disabled', function(i, v) { return !v; });
      }
  });
  $('input').on('ifUnchecked', function(event) {
    var all_unchecked = true;
    var form_inputs = $('form[name=client_call_request] > table td input[type=checkbox]');
    form_inputs.each(function() {
      if (this.checked){
        all_unchecked = false;
      }
    });
    if (all_unchecked) {
      btn_abrir_chamado.toggleClass('btn-default btn-primary');
      btn_abrir_chamado.prop('disabled', function(i, v) { return !v; });
    }
  });
  </script>
</body>
