<!-- Layout Dashboard-->
<!-- Bootstrap -->
<link href="../../App/View/css/bootstrap.min.css" rel="stylesheet">
<!-- Font Awesome -->
<link href="../../App/View/css/fontawesome-all.min.css" rel="stylesheet">
<script defer src="../../App/View/js/fontawesome-all.min.js"></script>
<!-- NProgress -->
<link href="../../App/View/css/nprogress.css" rel="stylesheet">

<!-- Custom Theme Style -->
<link href="../../App/View/css/custom.min.css" rel="stylesheet">
<link href="../../App/View/css/base-style.css" rel="stylesheet">
<link href="../../App/View/css/custom-style-override.css" rel="stylesheet">
<link href="../../App/View/css/custom-modal.css" rel="stylesheet">
<link href="../../App/View/css/autocomplete-custom-style.css" rel="stylesheet">
</head>

<body class="nav-md">
<div class="container body">
  <div class="main_container">

    <div class="col-md-3 left_col">
      <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
          <a href="../admin" class="site_title"><img src="../../App/View/img/logo.svg" id="sidebar-logo" alt="Logo"><span id="sidebar-logo-text"><span>TI</span> <span>CCHLA</span></span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
          <div class="profile_pic">
            <img src="" alt="..." class="img-circle profile_img">
          </div>
          <div class="profile_info">
              <span>Bem-vindo,</span>
              <h2><?php echo $_SESSION['user_name'];?></h2>
          </div>
        </div>
        <!-- /menu profile quick info -->

        <br />

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
           <div class="menu_section">
             <h3></h3>
             <ul class="nav side-menu">
               <li><a href="../admin"><i class="fas fa-home"></i> Início</a>
               </li>

               <li>
                 <a href="./solicitar_atendimento">
                   <span class="fa-layers fa-fw">
                     <i class="fas fa-user"></i>
                     <i class="fas fa-wrench" data-fa-transform="shrink-4 down-4.2 right-7" style="color:#2DA7F9;"></i>
                   </span> Solicitar atendimento
                 </a>
               </li>

               <li><a>
                 <span class="fa-layers fa-fw">
                   <i class="fas fa-user"></i>
                   <i class="fas fa-wrench" data-fa-transform="shrink-2 down-4.2 right-7" style="color:#2DA7F9;"></i>
                 </span> Equipe</a>
               </li>

               <li><a>
                 <span class="fa-layers fa-fw">
                   <i class="fas fa-users"></i>
                   <i class="fas fa-bullhorn" data-fa-transform="shrink-2 right-8 down-8" style="color:#2DA7F9;"></i>
                 </span> Clientes</a>
               </li>

               <li><a>
                   <span class="fa-layers fa-fw">
                     <i class="fas fa-list"></i>
                     <i class="fas fa-bullhorn" data-fa-transform="shrink-2 right-8 down-6" style="color:#2DA7F9;"></i>
                   </span> Chamados</a>
               </li>

               <li><a href="./cadastro_usuarios">
                 <span class="fa-layers fa-fw">
                   <i class="fas fa-user"></i>
                   <i class="fas fa-plus" data-fa-transform="shrink-7 right-12" style="color:#2DA7F9;"></i>
                 </span> Cadastro de Usuario</a>
               </li>

             </ul>
           </div>

         </div>
      </div>
    </div>

    <!-- top navigation -->
    <div class="top_nav">
      <div class="nav_menu">
        <nav>
          <div class="nav toggle">
            <a id="menu_toggle"><i class="fas fa-bars"></i></a>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <i class="fas fa-user"></i> <?php echo $_SESSION['user_name'];?>
                <span class="fas fa-angle-down"></span>
              </a>
              <ul class="dropdown-menu dropdown-usermenu pull-right">
                <li>
                  <a href="./configuracoes" data-original-title="Configurações da conta">
                    <i class="fas fa-wrench pull-right"></i> Configurações da conta
                  </a>
                </li>
                <li>
                  <a href="../logout" data-original-title="Sair">
                    <i class="fas fa-sign-out-alt pull-right"></i> Sair
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </nav>
      </div>
    </div>
    <!-- /top navigation -->

    <!-- page content -->

    <div class="right_col" role="main">
      <div class="">
        <div class="page-title">
          <div class="row tile_count">

          </div>
          <div class="row">
            <div class="col-xs-6">
              <div id="nova-solicitacao-panel" class="x_panel">
                <div class="x_title">
                  <h2>ABRIR CHAMADO <small>para cliente</small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fas fa-angle-up" data-fa-transform="grow-8"></i></a></li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                  <form class="form-horizontal form-label-left" name="solicitar_chamado" method="post">

                    <div class="form-group">
                      <label class="control-label col-md-3 col-sm-3 col-xs-12">Serviço</label>
                      <div class="col-md-9 col-sm-9 col-xs-12">
                        <input type="text" name="servico" class="form-control" placeholder="Digite para pesquisar uma opção ..." readonly>
                        <input type="text" id="id_servico" name="id_servico" hidden/>
                      </div>
                    </div>
                    <div class="form-group">
                      <label class="control-label col-md-3 col-sm-3 col-xs-12">Local</label>
                      <div class="col-md-9 col-sm-9 col-xs-12">
                        <input type="text" name="local" class="form-control" placeholder="Digite para pesquisar pelo local ..." readonly>
                        <input type="text" id="id_local" name="id_local" hidden/>
                      </div>
                    </div>
                    <div class="form-group">
                      <label class="control-label col-md-3 col-sm-3 col-xs-12">Cliente</label>
                      <div class="col-md-9 col-sm-9 col-xs-12">
                        <input type="text" name="usuario" class="form-control" placeholder="Digite para pesquisar pelo usuário ..." readonly>
                        <input type="text" id="id_usuario" name="id_usuario" hidden/>
                      </div>
                    </div>
                    <div class="form-group">
                      <label class="control-label col-md-3 col-sm-3 col-xs-12">Prazo</label>
                      <div class="col-md-9 col-sm-9 col-xs-12">
                        <input type="text" class="form-control" id="prazo_field" name="prazo_field">
                      </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Descrição</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                            <textarea id="descricao" name="descricao" class="form-control" placeholder="Detalhes e observações"></textarea>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                      <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                        <button type="reset" class="btn btn-default" disabled>Resetar campos</button>
                        <button type="submit" class="btn btn-default" disabled>Solicitar</button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
    </div>
    <!-- /page content -->

    <!-- footer content -->
    <!--<footer>

    </footer>-->
    <!-- /footer content -->
    <!-- SCRIPTS DASHBOARD THEME-->

  </div>
</div>
<!-- jQuery -->
<script src="../../App/View/js/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="../../App/View/js/bootstrap.min.js"></script>
<!-- NProgress -->
<script src="../../App/View/js/nprogress.js"></script>
<!-- Autosize -->
<script src="../../App/View/js/autosize.min.js"></script>
<script>
autosize($('textarea[name=descricao]'));
</script>

<!-- moment.js -->
<script src="../../App/View/js/moment.min.js"></script>

<!-- Default deadline  -->
<script>
var date = moment().add(2, 'days').format("DD/MM/YYYY");
var time = moment().format("HH:mm");
$('input[id=prazo_field]')[0].value = date + " às " + time;
</script>

<!-- jQuery autocomplete -->
<script src="../../App/View/js/jquery.autocomplete.min.js"></script>
<script>
  var servicos;
  var locais;
  var usuarios;

  var _formatRegexp = function(q) {
      q = q.replace(/[eéèêẽëEÉÈÊẼË]/gi,'[eéèêẽëEÉÈÊẼË]');
      q = q.replace(/[aáàâãäAÁÀÂÃÄÅÆ]/gi,'[aáàâãäAÁÀÂÃÄÅÆ]');
      q = q.replace(/[cçCÇ]/gi,'[cçCÇ]');
      q = q.replace(/[iíìîïIÌÍÎÏ]/gi,'[iíìîïIÌÍÎÏ]');
      q = q.replace(/[oóòôõöOÓÒÔÕÖ]/gi,'[oóòôõöOÓÒÔÕÖ]');
      q = q.replace(/[uúùûüUÚÙÛÜ]/gi,'[uúùûüUÚÙÛÜ]');
      q = q.replace(/[nñNÑ]/gi,'[nñNÑ]');
      q = q.replace(/[yYÿ^yÝ]/gi,'[yYÿ^yÝ]');
      return q;
  }

  var _autocompleteLookup = function (suggestion, originalQuery, queryLowerCase) {
          var pattern = '(\\b|)('+$.Autocomplete.utils.escapeRegExChars(queryLowerCase)+')';
          pattern = _formatRegexp(pattern);
          var matcher = new RegExp(pattern);
          var ret = suggestion.value.toLowerCase().match(matcher);
          return ret;
  };

  var _autocompleteFormatResult = function (suggestion, currentValue) {
          var pattern = '(\\b|)('+$.Autocomplete.utils.escapeRegExChars(currentValue)+')';
          pattern = _formatRegexp(pattern);
          return suggestion.value.replace(new RegExp(pattern, 'gi'), '<strong>$1$2<\/strong>');
  };

  $.post("/gtic/public/get_services_suggestions")
  .done(function(data) {
    servicos = data;
    $('form[name=solicitar_chamado] input[name=servico]').prop("readonly", false);
    $('form[name=solicitar_chamado] input[name=servico]').autocomplete({
        minChars: 0,
        lookup: servicos,
        groupBy: 'category',
        showNoSuggestionNotice: true,
        noSuggestionNotice: "Serviço não encontrado no sistema",
        lookupFilter: _autocompleteLookup,
        formatResult: _autocompleteFormatResult,
        onSelect: function (suggestion) {
            checkFormValidity();
            $('form[name=solicitar_chamado] input[id=id_servico]').val(suggestion.data.id_servico);
        }
    });
  })
  .fail(function() {
    alert("Houve um problema enquanto carregava os serviços");
  });

  $.post("/gtic/public/get_locales_suggestions")
  .done(function(data) {
    locais = data;
    $('form[name=solicitar_chamado] input[name=local]').prop("readonly", false);
    $('form[name=solicitar_chamado] input[name=local]').autocomplete({
        minChars: 0,
        lookup: locais,
        groupBy: 'category',
        showNoSuggestionNotice: true,
        noSuggestionNotice: "Local não reconhecido pelo sistema",
        lookupFilter: _autocompleteLookup,
        formatResult: _autocompleteFormatResult,
        onSelect: function (suggestion) {
            checkFormValidity();
            $('form[name=solicitar_chamado] input[id=id_local]').val(suggestion.data.id_local);
        }
    });
  })
  .fail(function() {
    alert("Houve um problema enquanto carregava os locais");
  });

  $.post("/gtic/public/get_users_suggestions")
  .done(function(data) {
    usuarios = data;
    $('form[name=solicitar_chamado] input[name=usuario]').prop("readonly", false);
    $('form[name=solicitar_chamado] input[name=usuario]').autocomplete({
        minChars: 0,
        lookup: usuarios,
        showNoSuggestionNotice: true,
        noSuggestionNotice: "Usuário não reconhecido pelo sistema",
        lookupFilter: _autocompleteLookup,
        formatResult: _autocompleteFormatResult,
        onSelect: function (suggestion) {
            checkFormValidity();
            $('form[name=solicitar_chamado] input[id=id_usuario]').val(suggestion.data.usuario_id);
        }
    });
  })
  .fail(function(data) {
      console.log(data);
    // alert("Houve um problema enquanto carregava os usuários");
  });
</script>

<!-- Custom Theme Scripts -->
<script src="../../App/View/js/custom.min.js"></script>

<!-- Simple message modal -->
<div class="modal fade" id="simple-modal" tabindex="-1" role="dialog" data-backdrop="false">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="simple-modal-title">Modal title</h4>
      </div>
      <div class="modal-body" id="simple-modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button id="simple-modal-secondary-button" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button id="simple-modal-primary-button" type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<script>
function setSimpleModalContent(title, body, primaryButtonAction, primaryButtonText = "Confirmar", secondaryButtonText = "Cancelar") {
  $('#simple-modal-title')[0].innerHTML = title;
  $('#simple-modal-body')[0].innerHTML = body;
  $('#simple-modal-primary-button')[0].innerHTML = primaryButtonText;
  $('#simple-modal-primary-button').off('click');
  $('#simple-modal-primary-button').on('click', primaryButtonAction);
  $('#simple-modal-secondary-button')[0].innerHTML = secondaryButtonText;
}
</script>

<!-- Check if request form can be submitted or reset -->
<script>
function checkFormValidity() {
    var servico = $('form[name=solicitar_chamado] input[name=servico]').val().replace(/^\s+/g, '').replace(/\s+$/g, '');
    var local = $('form[name=solicitar_chamado] input[name=local]').val().replace(/^\s+/g, '').replace(/\s+$/g, '');
    var descricao = $('form[name=solicitar_chamado] textarea[name=descricao]').val().replace(/^\s+/g, '').replace(/\s+$/g, '');

    // If at least one is not empty, enable reset button
    if (!servico.match(/^\s*$/) || !local.match(/^\s*$/) || !descricao.match(/^\s*$/)) {
      enableButton($('form[name=solicitar_chamado] button[type=reset]'));
    } else {
      disableButton($('form[name=solicitar_chamado] button[type=reset]'));
    }

    // If all inputs are filled, enable submit button
    if (!servico.match(/^\s*$/) && !local.match(/^\s*$/) && !descricao.match(/^\s*$/)) {
      enableButton($('form[name=solicitar_chamado] button[type=submit]'));
    } else {
      disableButton($('form[name=solicitar_chamado] button[type=submit]'));
    }
}

$("input[name=servico], textarea[name=descricao], input[name=local]").on("input", function() {
    checkFormValidity();
});
$("input[name=prazo_field]").on("input", function(e) {

});
$('form button[type=reset]').on('click', function() {
  disableButton($('form[name=solicitar_chamado] button[type=reset]'));
  disableButton($('form[name=solicitar_chamado] button[type=submit]'));
});

function enableButton(button) {
  button.removeClass("btn-default");
  button.addClass("btn-primary");
  button.prop("disabled", false);
}

function disableButton(button) {
  button.addClass("btn-default");
  button.removeClass("btn-primary");
  button.prop("disabled", true);
}

// On form reset
$('form[name=solicitar_chamado]').on("reset", function() {
  setTimeout(function() {
    var date = moment().add(2, 'days').format("DD/MM/YYYY");
    var time = moment().format("HH:mm");
    $('input[id=prazo_field]')[0].value = date + " às " + time;
  });
});

// On form submit
$('form[name=solicitar_chamado] button[type=submit]').on('click', function() {
  // Remove white space excess if any
  var descricao = $('form[name=solicitar_chamado] textarea[name=descricao]').val().replace(/^\s+/g, '').replace(/\s+$/g, '');
  $('form[name=solicitar_chamado] textarea[name=descricao]').val(descricao);

  // Adjust the deadline date
  var deadline_date = $('form[name=solicitar_chamado] input[name=prazo_field]')[0].value;
  var datetime;
  if (deadline_date.match(/\d{2}\/\d{2}\/\d{4} [aà]s \d{2}:\d{2}/)) {
    deadline_date = deadline_date.replace(/[aà]s /g, "");
    deadline_date += ":00";
    datetime = deadline_date.split(" ");
    var date = datetime[0].split("/");
    var time = datetime[1];
    datetime = date[2] + "-" + date[1] + "-" + date[0] + " " + time;
  }

  // Check if service is valid
  var service = $("input[name=servico]").val();
  var isServiceListed = ((servicos.filter(x => x.value === service)).length > 0);
  if (!isServiceListed) {
    alert("É preciso selecionar uma opção da lista de serviços");
    return false;
  }

  // Check if locale is valid
  var local = $("input[name=local]").val();
  var isLocaleListed = ((locais.filter(x => x.value === local)).length > 0);
  if (!isLocaleListed) {
    alert("É preciso selecionar uma opção da lista de locais");
    return false;
  }

  // Check if client is valid
  var cliente = $("input[name=usuario]").val();
  var isClientListed = ((usuarios.filter(x => x.value === cliente)).length > 0);
  if (!isClientListed) {
    alert("É preciso selecionar uma opção da lista de usuários");
    return false;
  }

  var id_servico = $('form[name=solicitar_chamado] input[id=id_servico]')[0].value;
  var id_local = $('form[name=solicitar_chamado] input[id=id_local]')[0].value;
  var id_cliente = $('form[name=solicitar_chamado] input[id=id_usuario]')[0].value;

  $("html").css("cursor", "wait");
  $("body").css("pointer-events", "none");

  $.post("/gtic/public/tecnico/register_call_request", {
    "id_servico": id_servico,
    "id_local": id_local,
    "id_usuario": id_cliente,
    "prazo": datetime,
    "descricao": descricao
  })
  .done(function(data) {
    $("html").css("cursor", "auto");
    $("body").css("pointer-events", "auto");

    alert("Chamado aberto com sucesso");
    $("form[name=solicitar_chamado]").trigger("reset");
  })
  .fail(function(data) {
    $("html").css("cursor", "auto");
    $("body").css("pointer-events", "auto");

    if (data.hasOwnProperty("responseJSON")) {
      var response = data.responseJSON;
      if (response.hasOwnProperty("event") && response.event === "error") {
        if (response.hasOwnProperty("type") && response.type === "deadline_wrong_format") {
          alert("O prazo foi informado em um formato não reconhecido");
        } else {
          alert("Houve um problema não previsto");
        }
      } else {
        alert("Houve um problema não previsto");
      }
    } else {
      alert("Houve um problema não previsto");
    }
  });
  return false;
});
</script>
</body>
