            </td>
                <td style="font-size: 0;"></td>
            </tr>

            <tr class="divider">
                <td class="divider-spacing"></td>
                <td class="divider-line" colspan="2"></td>
                <td class="divider-spacing"></td>
            </tr>

            <!-- FOOTER -->
            <tr id="footer-row">
                <td style="font-size: 0;"></td>
                <td id="gti-info">
                    <p>Contato:</p>
                    <p>
                        Telefone: 3342-2243<br>
                        Ramal: 112<br>
                        E-mail: email@email.com
                    </p>
                </td>
                <td id="footer-logos">
                    <a href="http://cchla.ufrn.br/" target="_blank">
                        <img id="footer-cchla-logo" src="PLACEHOLDER" />
                    </a>
                    <a href="http://ufrn.br/" target="_blank">
                        <img id="footer-ufrn-logo" src="PLACEHOLDER" />
                    </a>
                </td>
                <td style="font-size: 0;"></td>
            </tr>
        </tbody>
    </table>
</body>
</html>
