                                                        <tr>
                                                            <td style="color: #333; padding-right: 20px; padding-left: 20px;">
                                                                <p>
                                                                    <span style="font-weight: bold;">Atenciosamente,</span><br>
                                                                    <span style="color: #006F9A; font-weight: bold;">PLACEHOLDER_ENTITY_NAME.</span>
                                                                </p>
                                                            </td>
                                                        </tr>
                                                        <tr style="height: 16px;"></tr>
                                                    </tbody>
                                                </table>
                                            </td>
                                            <td width="20" style="background: url(PLACEHOLDER_SHADOW_IMG_EAST_URL) center left repeat-y;"></td>
                                        </tr>
                                        <tr>
                                            <td width="20" height="20" style="background: url(PLACEHOLDER_SHADOW_IMG_SOUTHWEST_URL) top right no-repeat;"></td>
                                            <td height="20" style="background: url(PLACEHOLDER_SHADOW_IMG_EAST_URL) top center repeat-x;"></td>
                                            <td width="20" height="20" style="background: url(PLACEHOLDER_SHADOW_IMG_SOUTHEAST_URL) top left no-repeat;"></td>
                                        </tr>
                                        <tr height="32px"></tr>
                                            <tr>
                                                <td></td>
                                                <td>
                                                    <table width="100%" style="color: #444; font-size: 0.8em;">
                                                        <tr>
                                                            <td align="left">
                                                                <p>Contato:</p>
                                                                <p>
                                                                    Telefone: PLACEHOLDER_TELEPHONE_NUMBER<br>
                                                                    Ramal: PLACEHOLDER_TELEPHONE_EXTENSION<br>
                                                                    E-mail: PLACEHOLDER_EMAIL</p>
                                                            </td>
                                                            <td align="right">
                                                                <table>
                                                                    <tr>
                                                                        <td style="text-align: center" width="135px" height="58px">
                                                                            <a href="#PLACEHOLDER_URL" target="_blank" style="text-decoration: none">
                                                                                <img style="width: 133px; height: 36px; padding-bottom: 16px; opacity: 0.75; image-rendering: auto; font-size: 1.85em; color: #666; font-weight: 900;" alt="PLACEHOLDER_LOGO_ALT" src="PLACEHOLDER_LOGO" />
                                                                            </a>
                                                                        </td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td style="text-align: center" width="135px" height="48px">
                                                                            <a href="#PLACEHOLDER_URL" target="_blank" style="text-decoration: none">
                                                                                <img style="width: 130px; height: 42px; image-rendering: auto; font-size: 1.85em; color: #666; font-weight: 900;" alt="PLACEHOLDER_LOGO_ALT" src="PLACEHOLDER_LOGO" />
                                                                            </a>
                                                                        </td>
                                                                    </tr>
                                                                </table>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                                <td></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
</body>
</html>
