<p>Bem-vind@, <span id="full-name-field"></span>!</p>
<p>Você já pode fazer login na sua conta do GTI Chamados.</p>
<p>A sua <strong>senha</strong> é seu nome de usuário + matrícula. Exemplo:</p>
<p>
    Usuário: maria<br>
    Matrícula: 123<br>
    A senha seria: maria123<br>
</p>
<p>Por questões de segurança, é recomendável que altere a senha o mais rápido possível. Para isso, após fazer login, acesse as configurações da conta.</p>
<p><a href="PLACEHOLDER" target="_blank">Clique aqui para acessar a plataforma</a></p>
<p>
    Atenciosamente,<br>
    GTI CCHLA.
</p>
