<tr>
    <td style="padding: 26px 20px;">
        <table width="100%" border="0" cellspacing="0" cellpadding="0" style="padding-bottom: 7px">
            <tbody>
                <tr>
                    <td align="left"><span style="color: #333; font-size: 1.45em;">Olá, <span id="full-name-field" style="color: #006F9A;"></span>!</span></td>
                    <td align="right" width="48px" height="38px">
                        <img style="width: 48px; height: 38px; image-rendering: pixelated; font-size: 1.85em; color: #006F9A; font-weight: 900;" data-imagetype="External" src="PLACEHOLDER_ENTITY_LOGO" alt="PLACEHOLDER_ENTITY_LOGO_ALT">
                    </td>
                </tr>
            </tbody>
        </table>
    </td>
</tr>
<tr>
    <td>
        <table width="100%" cellspacing="0" cellpadding="0" style="background-color: #006F9A;">
            <tbody>
                <tr>
                    <td style="text-align: center; line-height: 0; height: 120px;">
                        <img src="PLACEHOLDER_BANNER_REQUEST_GRANTED_IMG" alt="Sua conta está pronta!" width="100%" style=" color: #FFF; font-family: Lato, Roboto, Arial; font-size: 1.75em; font-weight: 500;">
                    </td>
                </tr>
            </tbody>
        </table>
    </td>
</tr>
<tr height="22px"></tr>
<tr>
    <td style="color: #333; padding-right: 20px; padding-left: 20px;">
        <p>A sua <strong>senha</strong> é seu nome de usuário + matrícula. Exemplo:</p>
    </td>
</tr>
<tr>
    <td style="color: #333; padding-right: 20px; padding-left: 20px;">
        <p>
            Usuário: maria<br>
            Matrícula: 123<br>
            A senha seria: maria123<br>
        </p>
    </td>
</tr>
<tr>
    <td style="color: #333; padding-right: 20px; padding-left: 20px;">
        <p>Por questões de segurança, é recomendável que altere a senha o mais rápido possível. Para isso, após fazer login, acesse as configurações da conta.</p>
    </td>
</tr>
<tr height="16px"></tr>
<tr>
    <td style="color: #333; padding-right: 20px; padding-left: 20px; text-align: center;">
        <a href="#PLACEHOLDER_PLATFORM_URL" target="_blank">
            <div style="color: #FFF; background-color: #006F9A; display: inline-block; padding: 16px 36px; border-radius: 24px;">
                <span>Acessar a plataforma</span>
            </div>
        </a>
    </td>
</tr>
<tr style="height: 16px;"></tr>
