<tr>
    <td style="padding: 26px 20px;">
        <table width="100%" border="0" cellspacing="0" cellpadding="0" style="padding-bottom: 7px">
            <tbody>
                <tr>
                    <td align="left"><span style="color: #333; font-size: 1.45em;">Prezad@ <span id="full-name-field" style="color: #006F9A;"></span>,</span></td>
                    <td align="right" width="48px" height="38px">
                        <img style="width: 48px; height: 38px; image-rendering: pixelated; font-size: 1.85em; color: #006F9A; font-weight: 900;" data-imagetype="External" src="PLACEHOLDER_ENTITY_LOGO" alt="PLACEHOLDER_ENTITY_LOGO_ALT">
                    </td>
                </tr>
            </tbody>
        </table>
    </td>
</tr>
<tr>
    <td style="color: #333; padding-right: 20px; padding-left: 20px;">
        <p>Infelizmente, sua conta não pôde ser efetivada pelo seguinte motivo:</p>
    </td>
</tr>
<tr>
    <td style="color: #FFF; background-color: #333; padding-right: 20px; padding-left: 20px;">
        <p id="refusal-reason-field"></p>
    </td>
</tr>
<tr style="height: 16px;"></tr>
<tr>
    <td style="color: #333; padding-right: 20px; padding-left: 20px;">
        <p>Se você acredita que houve um engano, sinta-se à vontade para responder esse e-mail!</p>
    </td>
</tr>
