<tr>
    <td style="padding: 26px 20px;">
        <table width="100%" border="0" cellspacing="0" cellpadding="0" style="padding-bottom: 7px">
            <tbody>
                <tr>
                    <td align="left"><span style="color: #333; font-size: 1.45em;">Olá, <span id="full-name-field" style="color: #006F9A;"></span>!</span></td>
                    <td align="right" width="48px" height="38px">
                        <img style="width: 48px; height: 38px; image-rendering: pixelated; font-size: 1.85em; color: #006F9A; font-weight: 900;" data-imagetype="External" src="PLACEHOLDER_ENTITY_LOGO" alt="PLACEHOLDER_ENTITY_LOGO_ALT">
                    </td>
                </tr>
            </tbody>
        </table>
    </td>
</tr>
<tr>
    <td style="padding-left: 20px; padding-right: 20px;">
        <table width="100%" cellspacing="0" cellpadding="0" style="background-color: #006F9A; padding: 36px 0px; border-radius: 12px">
            <tbody>
                <tr>
                    <td style="text-align: center; padding: 36px 0px;">
                        <span style="color: #FFF; font-family: Lato, Roboto, Arial; font-size: 1.75em; font-weight: 500;">Recebemos sua solicitação</span>
                        <div style="display: none; max-width: 0;">
                            <font size="1" color="white">
                                <span style="font-size: 1px;">
                                    <span style="">
                                        .
                                    </span>
                                </span>
                            </font>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </td>
</tr>
<tr height="22px"></tr>
<tr>
    <td style="color: #333; padding-right: 20px; padding-left: 20px;">
        <p>Apenas avisando que recebemos sua solicitação de cadastro no PLACEHOLDER_PLATFORM_NAME com os seguintes dados:</p>
    </td>
</tr>
<tr style="height: 16px;"></tr>
<tr>
    <td style="color: #FFF; background-color: #333; padding: 20px;">
        <table cellspacing="0" cellpadding="0">
            <tbody>
                <tr>
                    <td style="padding-left: 36px;">
                        <div>
                            <strong>Nome:</strong><br>
                            <strong>Sobrenome:</strong><br>
                            <strong>Usuário:</strong><br>
                            <strong>E-mail:</strong><br>
                            <strong>Unidade de lotação:</strong><br>
                            <strong>Matrícula SIAP:</strong>
                        </div>
                    </td>
                    <td style="padding-left: 36px;">
                        <div>
                            <span id="name-field"></span><br>
                            <span id="lastname-field"></span><br>
                            <span id="username-field"></span><br>
                            <span id="email-field"></span><br>
                            <span id="location-field"></span><br>
                            <span id="registration-number-field"></span>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </td>
</tr>
<tr style="height: 16px;"></tr>
<tr>
    <td style="color: #333; padding-right: 20px; padding-left: 20px;">
        <p>Enviaremos outro e-mail notificando da conclusão do cadastro.</p>
    </td>
</tr>
<tr>
    <td style="color: #333; padding-right: 20px; padding-left: 20px;">
        <p>Você pode responder esse e-mail caso queira notificar sobre algum problema nas informações passadas.</p>
    </td>
</tr>
<tr style="height: 16px;"></tr>
