<p>Olá, <span id="full-name-field"></span>!</p>
<p>Apenas avisando que recebemos sua solicitação de cadastro no GTI Chamados com os seguintes dados:</p>
<div id="fields-wrapper">
    <div id="field-titles">
        <strong>Nome:</strong><br>
        <strong>Sobrenome:</strong><br>
        <strong>Usuário:</strong><br>
        <strong>E-mail:</strong><br>
        <strong>Unidade de lotação:</strong><br>
        <strong>Matrícula SIAP:</strong>
    </div>
    <div id="value-fields">
        <span id="name-field"></span><br>
        <span id="lastname-field"></span><br>
        <span id="username-field"></span><br>
        <span id="email-field"></span><br>
        <span id="location-field"></span><br>
        <span id="registration-number-field"></span>
    </div>
</div>
<p>Enviaremos outro e-mail notificando da conclusão do cadastro.</p>
<p>Você pode responder esse e-mail caso queira notificar sobre algum problema nas informações passadas.</p>
<p>
    Atenciosamente,<br>
    GTI CCHLA.
</p>
