<!-- CSS Reset para resetar os estilos em todos os navegadores -->
<link rel="stylesheet" href="../App/View/css/css-reset.css">

<!-- Estilo base para todas as páginas -->
<link rel="stylesheet" href="../App/View/css/base-style.css">

<!-- Estilo da barra de navegação no topo -->
<link rel="stylesheet" href="../App/View/css/top-nav-style.css">

<!-- Estilo específico da página de login -->
<link rel="stylesheet" href="../App/View/css/login-page-style.css">

<!-- Font Awesome -->
<link rel="stylesheet" href="../App/View/css/fontawesome-all.min.css">
<script defer src="../App/View/js/fontawesome-all.min.js"></script>

<!-- iCheck -->
<link rel="stylesheet" href="../App/View/icheck/skins/square/blue.css">

<!-- Google Chrome Mobile App Color -->
<meta name="theme-color" content="#006699">
</head>

<body>

<!-- BARRA DE NAVEGAÇÃO -->
<header id="top-menu">
    <div class="top-menu-left-wrapper">
        <a class="top-menu-home-link no-user-select" onClick="window.location.reload()" tabindex="9">
            <!-- LOGO -->
            <span class="top-menu-logo-area">
                <span class="top-menu-logo-content">
                </span>
            </span>
        </a>

        <!-- HAMBURGER BUTTON -->
        <div class="top-menu-link-list-button-container no-user-select" style="display: none">
            <div onclick="toggleMenu()" class="top-menu-link-list-button" tabindex="10">
                <span class="fa-layers fa-2x">
                    <i id="hamburger-icon" class="fas fa-bars" title="Abrir menu"></i>
                    <i id="close-menu-icon" class="fas fa-times" title="Fechar menu"></i>
                </span>
            </div>
        </div>
    </div>

    <!-- LISTA DE LINKS -->
    <div class="top-menu-right-wrapper" style="display: none">
        <ul class="no-user-select">
            <li><a href="#" tabindex="11">Home</a></li>
            <li><a href="#features" tabindex="12">Serviços</a></li>
            <li><a href="#works" tabindex="13">Trabalhos</a></li>
            <li><a href="#team" tabindex="14">Equipe</a></li>
            <li><a href="#">Contato</a></li>
        </ul>
    </div>
</header>


<!-- ÁREA DO CONTEÚDO -->
<div id="content-area">

    <div id="content-wrapper" class="login-form-view">

        <!-- ÁREA DOS FORMULÁRIOS -->
        <div id="content-form-wrapper">

            <!-- ABAS -->
            <div id="sign-options-wrapper">

                <ul id="botoes-abas" class="no-user-select">
                    <li id="login_tab" class="selected" tabindex="1" role="button"><span>Acesso</span></li>
                    <li id="register_tab" tabindex="2" role="button"><span>Cadastro</span></li>
                </ul>
            </div>

            <!-- FORMULÁRIOS -->
            <div id="forms-wrapper">

                <!-- FORMULÁRIO DE LOGIN -->
                <form id="login-form" class="selected" action="logar" method="post" role="form">

                    <div class="form-input">
                        <i class="fas fa-user" title="Usuário"></i>
                        <input type="text" name="username" id="username" placeholder="Usuário" tabindex="3">
                    </div>

                    <div class="form-input">
                        <i class="fas fa-lock" title="Senha"></i>
                        <input type="password" name="password" id="password" placeholder="Senha" tabindex="4">
                    </div>

                    <!-- <div class="form-input">
                        <input type="checkbox" name="remember" id="remember" value="save_cred" tabindex="5">
                        <label for="remember"><span class="no-user-select">Lembrar meus dados</span></label>
                    </div> -->

                    <div class="form-input">
                        <input type="hidden" name="login_accept" value="login_accept"/>
                        <input type="submit" name="login-submit" id="login-submit" value="Acessar" tabindex="6">
                    </div>
                    <span class="no-user-select"><a href="#" tabindex="7">Esqueci meus dados de acesso</a></span>
                </form>

                <!-- FORMULÁRIO DE CADASTRO -->
                <form id="register-form" action="solicitar_acesso" method="post" role="form">

                    <div class="form-input" action="solicitar_acesso" method="post" role="form">
                        <input type="text" name="nomeCliente" id="nomeCliente" tabindex="3" placeholder="Nome">
                    </div>

                    <div class="form-input">
                        <input type="text" name="loginCliente" id="loginCliente" tabindex="4" placeholder="Usuário">
                    </div>

                    <div class="form-input">
                        <input type="text" name="emailCliente" id="emailCliente" tabindex="5" placeholder="E-mail">
                    </div>

                    <div class="form-input">
                        <input type="text" name="setorCliente" id="setorCliente" tabindex="6" placeholder="Unidade de Lotação">
                    </div>

                    <div class="form-input">
                        <input type="text" name="matriculaCliente" id="matriculaCliente" tabindex="7" placeholder="Matrícula SIAP">
                    </div>

                    <div class="form-input"><input type="submit" name="register-submit" id="register-submit" tabindex="8" value="Solicitar acesso"></div>
                </form>
            </div>
        </div>
    </div>
</div>




<!-- SCRIPTS -->

<!-- jQuery -->
<script src="../App/View/js/jquery.min.js"></script>
<!-- iCheck -->
<script src="../App/View/js/icheck.min.js"></script>
<script>
$(document).ready(function(){
  $('input').iCheck({
    checkboxClass: 'icheckbox_square-blue',
    radioClass: 'iradio_square'
  });
});
</script>
<!-- To avoid sticky hover -->
<script src="../App/View/js/no-sticky-hover.js"></script>
<!-- Responsible for the topnav -->
<script src="../App/View/js/nav-menu.js"></script>
<!-- Responsible for the forms -->
<script src="../App/View/js/login-page-form.js"></script>
</body>
<script>
$('#register-form, #login-form').submit(function(e) {
    var all_inputs_filled = true;
    $('#'+e.currentTarget.id+' input[type=text]').each(function() {
        if ($(this).val().match(/^\s*$/)) {
            all_inputs_filled = false;
            return false;
        }
    });
    if (all_inputs_filled) {
        return true;
    } else {
        alert("Preencha todos os campos");
        return false;
    }
});
</script>
