<!-- Google Font -->
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
<!-- CSS
================================================== -->
<!-- Fontawesome Icon font -->
    <link rel="stylesheet" href="../App/View/css/fontawesome-all.min.css">
<!-- Twitter Bootstrap css -->
    <link rel="stylesheet" href="../App/View/css/bootstrap.min.css">
<!-- jquery.fancybox  -->
    <link rel="stylesheet" href="../App/View/css/jquery.fancybox.css">
<!-- animate -->
    <link rel="stylesheet" href="../App/View/css/animate.css">
<!-- Main Stylesheet -->
    <link rel="stylesheet" href="../App/View/css/main.css">
<!-- media-queries -->
    <link rel="stylesheet" href="../App/View/css/media-queries.css">

<!-- Modernizer Script for old Browsers -->
    <script src="../App/View/js/modernizr-2.6.2.min.js"></script>
<!-- css do form-->
<link rel="stylesheet" href="../App/View/css/form.css">
</head>

<body id="body">
<section id="slider">
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">


      <!-- single slide -->
      <div class="item active" style="background-image: url(../App/View/img/banner.jpg);">
        <div class="carousel-caption">
          <div id="fullscreen_bg" class="fullscreen_bg"/>
          <div id="regContainer" class="container">
                <div class="row">
                <div class="col-md-6 col-md-offset-3">
                  <div class="panel panel-login">
                    <div class="panel-heading">
                      <div class="row">
                        <div class="col-xs-6">
                          <a href="#" class="active" id="login-form-link">Acessar</a>
                        </div>
                        <div class="col-xs-6">
                          <a href="#" id="register-form-link">Cadastro</a>
                        </div>
                      </div>
                      <hr>
                    </div>
                    <div class="panel-body">
                      <div class="row">
                        <div class="col-lg-12">
                          <form id="login-form" action="logar" method="post" role="form" style="display: block;">
                            <div class="form-group">
                              <label for="username">Username</label>
                              <input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Username" value="">
                            </div>
                            <div class="form-group">
                              <label for="password">Password</label>
                              <input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">
                            </div>
                            <div class="form-group text-center">
                              <input type="checkbox" tabindex="3" class="" name="remember" id="remember">
                              <label for="remember"> Remember Me</label>
                            </div>
                            <div class="form-group">
                              <div class="row">
                                <div class="col-sm-6 col-sm-offset-3">
                                  <input type="hidden" name="login_accept" value="login_accept"/>
                                  <input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value="login">
                                </div>
                              </div>
                            </div>
                          </form>
                          <form id="register-form" action="solicitar_acesso" method="post" role="form" style="display: none;">
                            <div class="form-group">
                              <label for="username">Nome</label>
                              <input type="text" name="nomeCliente" id="nomeCliente" tabindex="1" class="form-control" placeholder="Username" value="">
                            </div>
                            <div class="form-group">
                              <label for="email">E-mail</label>
                              <input type="email" name="emailCliente" id="emailCliente" tabindex="4" class="form-control" placeholder="E-mail">
                            </div>
                            <div class="form-group">
                              <label for="username">Login</label>
                              <input type="text" name="loginCliente" id="loginCliente" tabindex="1" class="form-control" placeholder="Username" value="">
                            </div>
                            <div class="form-group">
                              <label for="lotacao">Lotação</label>
                              <input type="text" name="setorCliente" id="setorCliente" tabindex="3" class="form-control" placeholder="Unidade de Lotação">
                            </div>
                            <div class="form-group">
                              <label for="matricula">Matrícula SIAP</label>
                              <input type="number" name="matriculaCliente" id="matriculaCliente" tabindex="2" class="form-control" placeholder="Matrícula">
                            </div>

                            <div class="form-group">
                              <div class="row">
                                <div class="col-sm-6 col-sm-offset-3">
                                  <input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-register" value="Solicitar Acesso">
                                </div>
                              </div>
                            </div>
                          </form>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>
      </div>
      <!-- end single slide -->

      <!-- single slide -->

      <!-- end single slide -->

    </div>
    <!-- End Wrapper for slides -->

  </div>
</section>
<!-- Essential jQuery Plugins
		================================================== -->
		<!-- Main jQuery -->
        <script src="../App/View/js/jquery-1.11.1.min.js"></script>
		<!-- Single Page Nav -->
        <script src="../App/View/js/jquery.singlePageNav.min.js"></script>
		<!-- Twitter Bootstrap -->
        <script src="../App/View/js/bootstrap.min.js"></script>
		<!-- jquery.fancybox.pack -->
        <script src="../App/View/js/jquery.fancybox.pack.js"></script>
		<!-- jquery.mixitup.min -->
        <script src="../App/View/js/jquery.mixitup.min.js"></script>
		<!-- jquery.parallax -->
        <script src="../App/View/js/jquery.parallax-1.1.3.js"></script>
		<!-- jquery.countTo -->
        <script src="../App/View/js/jquery-countTo.js"></script>
		<!-- jquery.appear -->
        <script src="../App/View/js/jquery.appear.js"></script>
		<!-- Contact form validation -->
		<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.32/jquery.form.js"></script>
		<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.11.1/jquery.validate.min.js"></script>
		<!-- Google Map -->
        <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
		<!-- jquery easing -->
        <script src="../App/View/js/jquery.easing.min.js"></script>
		<!-- jquery easing -->
        <script src="../App/View/js/wow.min.js"></script>
		<script>
			var wow = new WOW ({
				boxClass:     'wow',      // animated element css class (default is wow)
				animateClass: 'animated', // animation css class (default is animated)
				offset:       120,          // distance to the element when triggering the animation (default is 0)
				mobile:       false,       // trigger animations on mobile devices (default is true)
				live:         true        // act on asynchronously loaded content (default is true)
			  }
			);
			wow.init();
		</script>
		<!-- Custom Functions -->
        <script src="../App/View/js/custom.js"></script>

		<script type="text/javascript">
			$(function(){
				/* ========================================================================= */
				/*	Contact Form
				/* ========================================================================= */

				$('#contact-form').validate({
					rules: {
						name: {
							required: true,
							minlength: 2
						},
						email: {
							required: true,
							email: true
						},
						message: {
							required: true
						}
					},
					messages: {
						name: {
							required: "come on, you have a name don't you?",
							minlength: "your name must consist of at least 2 characters"
						},
						email: {
							required: "no email, no message"
						},
						message: {
							required: "um...yea, you have to write something to send this form.",
							minlength: "thats all? really?"
						}
					},
					submitHandler: function(form) {
						$(form).ajaxSubmit({
							type:"POST",
							data: $(form).serialize(),
							url:"process.php",
							success: function() {
								$('#contact-form :input').attr('disabled', 'disabled');
								$('#contact-form').fadeTo( "slow", 0.15, function() {
									$(this).find(':input').attr('disabled', 'disabled');
									$(this).find('label').css('cursor','default');
									$('#success').fadeIn();
								});
							},
							error: function() {
								$('#contact-form').fadeTo( "slow", 0.15, function() {
									$('#error').fadeIn();
								});
							}
						});
					}
				});
			});
		</script>
		<script type="text/javascript">
			$(function() {

    			$('#login-form-link').click(function(e) {
				$("#login-form").delay(100).fadeIn(100);
 				$("#register-form").fadeOut(100);
				$('#register-form-link').removeClass('active');
				$(this).addClass('active');
				e.preventDefault();
			});
			$('#register-form-link').click(function(e) {
				$("#register-form").delay(100).fadeIn(100);
 				$("#login-form").fadeOut(100);
				$('#login-form-link').removeClass('active');
				$(this).addClass('active');
				e.preventDefault();
			});

			});
		</script>
<!--
End Home SliderEnd
==================================== -->
</body>
